This notebook joins all of the datasets together and cleans up/ averages the player stats.

In [281]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk

In [282]:
# Read in the data
recruit_scores = pd.read_csv(r'../Data/qb_trait_scores.csv')

In [283]:
# Examine null values per column
recruit_scores.isna().sum()

player                        0
url                           0
rank                          0
height                        0
weight                        0
composite_rating              0
school_info                   0
city                          0
state                         0
draft_projection              9
reminds_of                   36
evaluated_date                0
analyst                      15
athletic_background           0
committed_school              0
numerical_rating              0
Is_FBS                        0
Is_SEC                        0
Is_Big_Ten                    0
Is_Big_XII                    0
Is_ACC                        0
pos_DUAL                      0
pos_PRO                       0
pos_QB                        0
star_2                        0
star_3                        0
star_4                        0
star_5                        0
Is_Top_Five_Ranked            0
Is_From_East                  0
Is_From_West                  0
weight_to_height_ratio        0
bmi                           0
Accuracy                     21
Arm Strength                 23
Decision Making              87
Football IQ                 107
Leadership & Intangibles    104
Mobility & Athleticism       14
NFL / Draft Projection       17
Pocket Presence              29
Size & Physical              24
dtype: int64

Note lot of prospects are missing certain trait categories. Specifically Football IQ, Decision Making and Leadership & Intangibles. These columns will be dropped and because of the much lower amount of missingness in the other columns, any players with missing data in the following will be dropped: Accuracy, Arm Strength, Mobility & Athleticism, Pocket Presence, Size & Physical

In [284]:
# Drop columns with lots of missing info
recruit_scores = recruit_scores.drop(columns=['Football IQ', 'Decision Making', 'Leadership & Intangibles'])


# Drop rows with missing values in the indicated columns
recruit_scores = recruit_scores.dropna(subset=['Accuracy', 'Arm Strength', 'Mobility & Athleticism', 'Pocket Presence', 'Size & Physical'])

In [285]:
# Check new results of null values per column
recruit_scores.isna().sum()

player                     0
url                        0
rank                       0
height                     0
weight                     0
composite_rating           0
school_info                0
city                       0
state                      0
draft_projection           8
reminds_of                20
evaluated_date             0
analyst                   10
athletic_background        0
committed_school           0
numerical_rating           0
Is_FBS                     0
Is_SEC                     0
Is_Big_Ten                 0
Is_Big_XII                 0
Is_ACC                     0
pos_DUAL                   0
pos_PRO                    0
pos_QB                     0
star_2                     0
star_3                     0
star_4                     0
star_5                     0
Is_Top_Five_Ranked         0
Is_From_East               0
Is_From_West               0
weight_to_height_ratio     0
bmi                        0
Accuracy                   0
Arm Strength               0
Mobility & Athleticism     0
NFL / Draft Projection     8
Pocket Presence            0
Size & Physical            0
dtype: int64

### Let's look at player stats_2018_2025


ultimately, we want to look at the success players achieve at the original school they were recruited to. To do this, we will id players who have at least 2 years at the school they were recruited to and aggregated their stats together. This way we can train out models on multiple years of data for a player.

In [286]:
# Read in the data
qb_stats = pd.read_csv(r'../Data/player_stats_2018_2025.csv', encoding='latin1')

In [287]:
qb_stats[qb_stats['Player'] == 'Jayden Daniels']

,Rk,Player,Team,Conf,G,Cmp,Att,Cmp%,Yds,TD,TD%,Int,Int%,Y/A,AY/A,Y/C,Y/G,Rate,Awards,Year
1128,129,Jayden Daniels,Arizona State,Pac-12,4,12.3,21.0,58.3,175.3,1.25,6.0,0.25,1.2,8.3,9.0,14.3,175.3,145.7,NaN,2020

In [288]:
# look at the data output
qb_stats

,Rk,Player,Team,Conf,G,Cmp,Att,Cmp%,Yds,TD,TD%,Int,Int%,Y/A,AY/A,Y/C,Y/G,Rate,Awards,Year
0,1,Dwayne Haskins*,Ohio State,Big Ten,14,26.6,38.10,70.0,345.1,3.57,9.4,0.57,1.5,9.1,10.26,13.0,345.1,174.1,H-3,2018
1,2,Gardner Minshew*,Washington State,Pac-12,13,36.0,50.90,70.7,367.6,2.92,5.7,0.69,1.4,7.2,7.76,10.2,367.6,147.6,H-5,2018
2,3,Kyler Murray*,Oklahoma,Big 12,14,18.6,26.90,69.0,311.5,3.00,11.1,0.50,1.9,11.6,12.96,16.8,311.5,199.2,H-1,2018
3,4,Taylor Cornelius*,Oklahoma State,Big 12,13,22.2,37.30,59.4,306.0,2.46,6.6,1.00,2.7,8.2,8.32,13.8,306.0,144.7,NaN,2018
4,5,Tua Tagovailoa*,Alabama,SEC,15,16.3,23.70,69.0,264.4,2.87,12.1,0.40,1.7,11.2,12.83,16.2,264.4,199.4,"H-2,Maxwell,AA,Camp",2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,496,Gavin Freeman,Oklahoma State,Big 12,12,0.0,0.08,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,NaN,0.0,0.0,NaN,2025
3932,497,Grady Gross*,Washington,Big Ten,13,0.0,0.08,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,NaN,0.0,0.0,NaN,2025
3933,498,Grant Page*,Southern Mississippi,Sun Belt,11,0.0,0.09,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,NaN,0.0,0.0,NaN,2025
3934,499,Holden Geriner*,Texas State,Sun Belt,3,0.0,0.33,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,NaN,0.0,0.0,NaN,2025
3935,500,Isaac Wilson*,Utah,Big 12,1,0.0,1.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,NaN,0.0,0.0,NaN,2025

In [289]:
# Take out all asterisks from player names
qb_stats['Player'] = qb_stats['Player'].str.replace('*', '', regex=False)

In [290]:
# Examine how many entries there are for each player/ team combo
qb_stats.groupby(['Player','Team']).size().sort_values(ascending=False)

Player            Team
Chandler Fields   Louisiana         6
Jalon Daniels     Kansas            6
Gunnar Watson     Troy              6
Brett Gabbert     Miami (OH)        6
Tyler Page        SMU               6
                                   ..
Zeb Noland        South Carolina    1
                  Iowa State        1
Zavion Thomas     LSU               1
Zane Flores       Oklahoma State    1
Zakhari Franklin  UTSA              1
Length: 2453, dtype: int64

In [291]:
qb_stats.columns

Index(['Rk', 'Player', 'Team', 'Conf', 'G', 'Cmp', 'Att', 'Cmp%', 'Yds', 'TD',
       'TD%', 'Int', 'Int%', 'Y/A', 'AY/A', 'Y/C', 'Y/G', 'Rate', 'Awards',
       'Year'],
      dtype='str')

note: columns that will be averaged across seasons are 'G', 'Cmp', 'Att', 'Cmp%', 'Yds', 'TD', 'TD%', 'Int', 'Int%', 
             'Y/A', 'AY/A', 'Y/C', 'Y/G', 'Rate'

the column that will be kept the same are the 'Player', 'Team', and 'Conf' columns. Note: keep_cols below only contains 'Conf' because the 'Player' and 'Team' combos are already implemented by the .groupby() function.

In [292]:
# Find players with multiple rows but were with the same team (indicating multiple years of stats for that player/ team combo)
multi_year_players = qb_stats.groupby(['Player','Team']).filter(lambda x: len(x) > 1)

# Average the stat columns, keep first value of categorical columns
stat_cols = ['G', 'Cmp', 'Att', 'Cmp%', 'Yds', 'TD', 'TD%', 'Int', 'Int%', 
             'Y/A', 'AY/A', 'Y/C', 'Y/G', 'Rate']
keep_cols = ['Conf']

averaged_df = (
    multi_year_players
    .groupby(['Player','Team'])
    .agg({**{col: 'mean' for col in stat_cols},
          **{col: 'first' for col in keep_cols}})
    .reset_index()
)

# Reorder columns to match original: Player, Team, Conf, stats...
averaged_df = averaged_df[['Player', 'Team', 'Conf'] + stat_cols]

In [293]:
# Check row count after averaging
averaged_df.shape

(928, 17)

In [294]:
averaged_df

,Player,Team,Conf,G,Cmp,Att,Cmp%,Yds,TD,TD%,Int,Int%,Y/A,AY/A,Y/C,Y/G,Rate
0,AJ Bianco,Nevada,MWC,7.666667,3.843333,6.533333,60.533333,43.40,0.266667,3.766667,0.243333,2.766667,6.30,5.793333,10.466667,43.40,120.233333
1,AJ Hairston,Massachusetts,Ind,7.000000,10.350000,19.950000,52.150000,107.85,0.825000,4.350000,0.200000,0.950000,5.50,5.960000,10.450000,107.85,110.900000
2,AJ Mayer,Miami (OH),MAC,5.000000,8.690000,17.100000,50.650000,122.30,1.095000,6.500000,0.310000,1.800000,7.15,7.615000,14.100000,122.30,128.350000
3,AJ Padgett,Rice,CUSA,4.500000,12.400000,22.600000,55.650000,165.75,1.500000,6.650000,0.665000,3.200000,7.20,7.085000,13.250000,165.75,131.700000
4,AJ Swann,Vanderbilt,SEC,7.500000,15.300000,27.350000,56.350000,192.20,1.555000,5.600000,0.695000,2.300000,6.90,7.020000,12.350000,192.20,128.450000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,Zamar Wise,Massachusetts,Ind,5.000000,1.095000,2.645000,50.000000,8.92,0.000000,0.000000,0.000000,0.000000,3.05,3.055000,7.350000,8.90,75.650000
924,Zeon Chriss,Houston,Big 12,8.500000,4.610000,7.650000,55.700000,46.45,0.265000,3.950000,0.450000,5.500000,5.70,4.065000,10.350000,46.45,105.950000
925,Zeon Chriss,Louisiana,Sun Belt,6.000000,7.525000,11.425000,63.350000,90.05,0.815000,6.950000,0.440000,5.000000,7.65,6.775000,12.050000,90.05,140.300000
926,Zevi Eckhaus,Washington State,Ind,7.000000,14.900000,22.300000,68.450000,165.85,1.345000,6.450000,0.880000,3.950000,7.65,7.160000,11.150000,165.85,146.050000
927,Zion Turner,Connecticut,Ind,7.500000,6.250000,11.150000,48.900000,56.10,0.345000,1.750000,0.385000,1.950000,3.55,3.005000,6.700000,56.10,80.350000

We also want to save information regarding how many seasons each player played for a team. We can simply do this by saving the count from earlier and assigning it to each player

In [295]:
# save into dataframe
qb_counts = pd.DataFrame(qb_stats.groupby(['Player','Team']).size().reset_index(name='Counts'))

In [296]:
# look at results
qb_counts

            Player                Team  Counts
0       A.J. Davis                 UAB       1
1      A.J. Erdely                 UAB       1
2        AJ Bianco              Nevada       3
3          AJ Bush            Illinois       1
4         AJ Duffy       Florida State       1
...            ...                 ...     ...
2448   Zeon Chriss           Louisiana       2
2449  Zevi Eckhaus    Washington State       2
2450   Zion Turner         Connecticut       2
2451   Zion Turner            Marshall       1
2452     Zion Webb  Jacksonville State       1

[2453 rows x 3 columns]

In [297]:
# test an example player
qb_counts[qb_counts['Player'] == 'Sam Hartman']

           Player         Team  Counts
2069  Sam Hartman   Notre Dame       1
2070  Sam Hartman  Wake Forest       5

In [298]:
# Merge the averaged stats with the counts of entries per player/ team combo
merged_df = pd.merge(averaged_df, qb_counts, on=['Player', 'Team'], how='inner')

In [299]:
merged_df[merged_df['Player'] == 'Sam Hartman']

,Player,Team,Conf,G,Cmp,Att,Cmp%,Yds,TD,TD%,Int,Int%,Y/A,AY/A,Y/C,Y/G,Rate,Counts
776,Sam Hartman,Wake Forest,ACC,9.6,18.66,31.78,58.44,257.08,2.036,6.2,0.79,2.44,8.08,8.236,13.84,257.08,142.0,5

Note: Notre Dame Sam Hartman was removed from the data during the average_df creation because he only played 1 year there.

With this, lets merge this data with the recruit_scores data.

In [300]:
recruit_scores.columns

Index(['player', 'url', 'rank', 'height', 'weight', 'composite_rating',
       'school_info', 'city', 'state', 'draft_projection', 'reminds_of',
       'evaluated_date', 'analyst', 'athletic_background', 'committed_school',
       'numerical_rating', 'Is_FBS', 'Is_SEC', 'Is_Big_Ten', 'Is_Big_XII',
       'Is_ACC', 'pos_DUAL', 'pos_PRO', 'pos_QB', 'star_2', 'star_3', 'star_4',
       'star_5', 'Is_Top_Five_Ranked', 'Is_From_East', 'Is_From_West',
       'weight_to_height_ratio', 'bmi', 'Accuracy', 'Arm Strength',
       'Mobility & Athleticism', 'NFL / Draft Projection', 'Pocket Presence',
       'Size & Physical'],
      dtype='str')

In [301]:
merged_df.columns

Index(['Player', 'Team', 'Conf', 'G', 'Cmp', 'Att', 'Cmp%', 'Yds', 'TD', 'TD%',
       'Int', 'Int%', 'Y/A', 'AY/A', 'Y/C', 'Y/G', 'Rate', 'Counts'],
      dtype='str')

In [302]:
# merge the data
players = pd.merge(recruit_scores, merged_df, left_on=['player','committed_school'], right_on=['Player', 'Team'], how='inner')

In [303]:
players.shape

(48, 57)

In [304]:
players

,player,url,rank,height,weight,composite_rating,school_info,city,state,draft_projection,...,TD,TD%,Int,Int%,Y/A,AY/A,Y/C,Y/G,Rate,Counts
0,Arch Manning,https://247sports.com/player/arch-manning-4608...,1,76.0,215,100,"Isidore Newman (New Orleans, LA)",New Orleans,LA,Round 1 - Top 10,...,0.966667,5.466667,0.246667,1.300000,8.066667,8.590000,14.400000,117.400000,139.766667,3
1,Athan Kaliakmanis,https://247sports.com/player/athan-kaliakmanis...,26,76.0,205,90,"Antioch (Antioch, IL)",Antioch,IL,4-7 Round - Day 3,...,0.720000,3.750000,0.555000,3.350000,7.400000,6.635000,13.800000,119.600000,121.300000,2
2,Austin Novosad,https://247sports.com/player/austin-novosad-46...,13,75.0,185,94,"Dripping Springs (Dripping Springs, TX)",Dripping Springs,TX,2-3 Round - Day 2,...,0.000000,0.000000,0.000000,0.000000,9.400000,9.410000,16.433333,19.866667,156.300000,3
3,Avery Johnson,https://247sports.com/player/avery-johnson-461...,9,74.0,175,95,"Maize (Maize, KS)",Maize,KS,4-7 Round - Day 3,...,1.350000,6.533333,0.423333,1.500000,7.200000,7.816667,12.366667,155.766667,136.966667,3
4,Beau Allen,https://247sports.com/player/beau-allen-46039461/,64,74.0,203,85,"Lexington Catholic (Lexington, KY)",Lexington,KY,Power 4 Starter,...,0.000000,0.000000,0.000000,0.000000,6.700000,6.690000,12.400000,25.350000,111.000000,2
5,Behren Morton,https://247sports.com/player/behren-morton-460...,11,74.0,185,94,"Eastland (Eastland, TX)",Eastland,TX,4-7 Round - Day 3,...,1.272000,4.320000,0.528000,1.960000,5.640000,5.612000,9.060000,161.880000,113.960000,5
6,Brian Maurer,https://247sports.com/player/brian-maurer-4603...,24,75.0,199,88,"West Port (Ocala, FL)",Ocala,FL,Power 4 Starter,...,0.125000,1.350000,0.315000,3.350000,4.350000,3.125000,10.000000,34.950000,74.300000,2
7,Brock Glenn,https://247sports.com/player/brock-glenn-46114...,21,74.0,195,90,"Lausanne Collegiate School (Covington, TN)",Covington,TN,4-7 Round - Day 3,...,0.356667,7.833333,0.370000,2.766667,5.533333,5.863333,11.766667,49.466667,114.200000,3
8,Brock Vandagriff,https://247sports.com/player/brock-vandagriff-...,5,75.0,205,97,"Prince Avenue Christian School (Bogart, GA)",Bogart,GA,Second Round,...,0.083333,3.700000,0.000000,0.000000,3.066667,3.796667,13.800000,6.866667,60.100000,3
9,Bryce Young,https://247sports.com/player/bryce-young-93127/,1,71.0,183,101,"Mater Dei (Santa Ana, CA)",Santa Ana,CA,Round 1 - Top 10,...,1.976667,7.166667,0.296667,0.866667,8.266667,9.300000,12.966667,207.200000,154.800000,3
10,C.J. Stroud,https://247sports.com/player/cj-stroud-46038118/,3,74.5,194,98,"Rancho Cucamonga (Rancho Cucamonga, CA)",Rancho Cucamonga,CA,First Round,...,3.410000,10.250000,0.480000,1.450000,9.800000,11.165000,14.150000,326.650000,182.150000,2
11,Cade Klubnik,https://247sports.com/player/cade-klubnik-4605...,2,74.5,186,98,"Austin Westlake (Austin, TX)",Austin,TX,First Round,...,1.390000,4.425000,0.480000,1.925000,7.075000,7.070000,11.125000,198.425000,133.400000,4
12,Cade McNamara,https://247sports.com/player/cade-mcnamara-93369/,15,73.0,206,90,"Damonte Ranch (Reno, NV)",Reno,NV,4-7 Round - Day 3,...,0.883333,5.200000,0.253333,1.933333,7.033333,7.186667,11.700000,116.766667,132.566667,3
13,Cameron Edge,https://247sports.com/player/cameron-edge-4609...,60,73.0,190,86,"Smyrna (Smyrna, DE)",Smyrna,DE,Power 4 Starter,...,0.500000,11.800000,0.250000,5.550000,9.750000,9.605000,15.050000,41.750000,174.250000,2
14,Carson Beck,https://247sports.com/player/carson-beck-46053...,13,76.5,226,92,"Mandarin (Jacksonville, FL)",Jacksonville,FL,4-7 Round - Day 3,...,1.232500,8.050000,0.462500,3.200000,8.475000,8.597500,13.625000,159.475000,154.675000,4
15,Christopher Vizzina,https://247sports.com/player/christopher-vizzi...,10,75.0,211,95,"Briarwood Christian (Birmingham, AL)",Birmingham,AL,2-3 Round - Day 2,...,0.400000,2.800000,0.100000,0.700000,5.650000,5.900000,9.500000,54.150000,115.000000,2
16,Devin Brown,https://247sports.com/player/devin-brown-46084...,5,74.5,196,97,"Corner Canyon (Draper, UT)",Draper,UT,2-3 Round - Day 2,...,0.220000,6.050000,0.085000,1.800000,6.750000,7.135000,12.000000,24.450000,129.050000,2
17,Drew Allar,https://247sports.com/player/drew-allar-46096466/,1,76.5,232,100,"Medina (Medina, OH)",Medina,OH,First Round,...,1.287500,6.050000,0.287500,1.100000,6.950000,7.680000,11.125000,157.000000,138.650000,4
18,Dylan Lonergan,https://247sports.com/player/dylan-lonergan-46...,16,74.0,215,91,"Brookwood (Snellville, GA)",Snellville,GA,Power 4 Starter,...,0.000000,0.000000,0.000000,0.000000,4.900000,4.915000,5.300000,11.750000,132.950000,2
19,Garrett Nussmeier,https://247sports.com/player/garrett-nussmeier...,19,73.5,182,94,"Flower Mound Marcus (Flower Mound, TX)",Flower Mound,TX,4-7 Round - Day 3,...,1.068000,4.860000,0.538000,2.720000,7.460000,7.204000,12.180000,161.360000,134.380000,5
20,Gavin Wimsatt,https://247sports.com/player/gavin-wimsatt-460...,25,75.0,200,91,"Owensboro (Owensboro, KY)",Owensboro,KY,4-7 Round - Day 3,...,0.440000,2.166667,0.666667,5.700000,4.433333,2.326667,9.733333,79.800000,78.366667,3
21,Graham Mertz,https://247sports.com/player/graham-mertz-4603...,7,75.0,205,93,"Blue Valley North (Mission, KS)",Mission,KS,4-7 Round - Day 3,...,0.910000,3.700000,0.597500,2.500000,7.025000,6.640000,10.800000,135.500000,133.200000,4
22,Gunner Stockton,https://247sports.com/player/gunner-stockton-4...,7,73.0,220,94,"Rabun County (Tiger, GA)",Tiger,GA,2-3 Round - Day 2,...,0.803333,6.100000,0.270000,2.733333,7.400000,7.390000,10.966667,110.566667,144.500000,3
23,Harrison Bailey,https://247sports.com/player/harrison-bailey-8...,8,77.0,211,95,"Marietta (Marietta, GA)",Marietta,GA,2-3 Round - Day 2,...,0.335000,2.950000,0.165000,1.450000,5.400000,5.320000,8.650000,56.150000,108.800000,2
24,Haynes King,https://247sports.com/player/haynes-king-46049...,10,74.5,189,95,"Longview (Longview, TX)",Longview,TX,NaN,...,0.890000,11.466667,1.000000,12.266667,9.966667,6.730000,18.266667,127.600000,153.133333,3
25,Heinrich Haarberg,https://247sports.com/player/heinrich-haarberg...,40,77.0,185,88,"Kearney Catholic (Kearney, NE)",Kearney,NE,Power 4 Starter,...,0.350000,2.250000,0.390000,5.050000,5.900000,4.075000,11.350000,52.550000,99.100000,2
26,Hudson Card,https://247sports.com/player/hudson-card-46048...,6,74.5,179,95,"Lake Travis (Austin, TX)",Austin,TX,2-3 Round - Day 2,...,0.376667,3.866667,0.070000,0.700000,5.800000,6.243333,9.666667,51.200000,114.666667,3
27,J.J. McCarthy,https://247sports.com/player/jj-mccarthy-46042...,6,75.0,190,97,"IMG Academy (La Grange Park, IL)",La Grange Park,IL,Second Round,...,1.163333,7.300000,0.270000,2.066667,8.700000,9.273333,13.600000,146.833333,158.233333,3
28,Jackson Arnold,https://247sports.com/player/jackson-arnold-46...,4,73.0,205,99,"Denton Guyer (Denton, TX)",Denton,TX,First Round,...,0.885000,5.350000,0.365000,2.750000,7.000000,6.780000,11.000000,111.250000,133.750000,2
29,Jalen Milroe,https://247sports.com/player/jalen-milroe-4605...,14,75.0,206,94,"Katy Tompkins (Katy, TX)",Katy,TX,4-7 Round - Day 3,...,0.970000,9.200000,0.422500,2.800000,7.600000,8.167500,13.100000,121.050000,146.400000,4
30,Jayden Daniels,https://247sports.com/player/jayden-daniels-89...,2,75.0,175,97,"Cajon (San Bernardino, CA)",San Bernardino,CA,Second Round,...,1.146667,4.766667,0.396667,1.700000,8.300000,8.510000,13.600000,201.233333,143.700000,3
31,Kedon Slovis,https://247sports.com/player/kedon-slovis-4604...,75,74.0,186,84,"Desert Mountain (Scottsdale, AZ)",Scottsdale,AZ,4-7 Round - Day 3,...,2.183333,5.933333,0.936667,2.566667,7.800000,7.860000,11.500000,283.733333,148.133333,3
32,Kenny Minchey,https://247sports.com/player/kenny-minchey-461...,14,73.5,215,93,"Pope John Paul II (Hendersonville, TN)",Hendersonville,TN,4-7 Round - Day 3,...,0.000000,0.000000,0.000000,0.000000,5.833333,5.846667,6.600000,13.566667,141.400000,3
33,Kyle McCord,https://247sports.com/player/kyle-mccord-46047...,8,75.0,215,97,"St. Joseph's Prep (Philadelphia, PA)",Philadelphia,PA,Second Round,...,0.846667,5.733333,0.300000,2.333333,9.833333,9.946667,14.100000,124.833333,167.500000,3
34,Luke Altmyer,https://247sports.com/player/luke-altmyer-4605...,30,74.0,190,90,"Starkville (Starkville, MS)",Starkville,MS,NaN,...,0.350000,7.250000,0.325000,5.650000,6.300000,5.180000,12.600000,34.850000,115.850000,2
35,Marcel Reed,https://247sports.com/player/marcel-reed-46102...,20,73.0,175,90,"Montgomery Bell Academy (Nashville, TN)",Nashville,TN,NaN,...,1.203333,5.233333,0.600000,2.833333,8.866667,8.626667,14.666667,179.333333,146.500000,3
36,Nico Iamaleava,https://247sports.com/player/nico-iamaleava-46...,2,77.0,195,100,"Warren (Long Beach, CA)",Long Beach,CA,NaN,...,0.930000,5.050000,0.190000,0.750000,7.400000,8.085000,11.750000,132.000000,140.400000,2
37,Noah Fifita,https://247sports.com/player/noah-fifita-46081...,40,70.0,170,87,"Servite (Anaheim, CA)",Anaheim,CA,Power 4 Starter,...,1.535000,5.950000,0.490000,1.500000,7.425000,7.957500,12.300000,194.150000,140.225000,4
38,Preston Stone,https://247sports.com/player/preston-stone-460...,18,74.0,205,94,"Parish Episcopal School (Dallas, TX)",Dallas,TX,4-7 Round - Day 3,...,0.842500,5.525000,0.202500,1.450000,7.275000,7.720000,12.850000,99.800000,131.350000,4
39,Rickie Collins,https://247sports.com/player/rickie-collins-46...,15,74.0,190,92,"Woodlawn (Baton Rouge, LA)",Baton Rouge,LA,4-7 Round - Day 3,...,0.000000,0.000000,0.000000,0.000000,4.250000,4.250000,4.250000,7.350000,135.700000,2
40,Riley Leonard,https://247sports.com/player/riley-leonard-461...,58,76.0,203,86,"Fairhope (Fairhope, AL)",Fairhope,AL,Power 4 Starter,...,0.703333,2.833333,0.343333,1.633333,6.800000,6.620000,11.266667,146.666667,123.500000,3
41,Ryan Hilinski,https://247sports.com/player/ryan-hilinski-93478/,6,75.0,230,94,"Orange Lutheran (Orange, CA)",Orange,CA,4-7 Round - Day 3,...,0.500000,1.350000,0.225000,0.600000,5.750000,5.730000,9.250000,115.650000,113.850000,2
42,Sam Howell,https://247sports.com/player/sam-howell-91707/,4,72.0,225,95,"Sun Valley (Monroe, NC)",Monroe,NC,2-3 Round - Day 2,...,2.473333,8.166667,0.623333,2.100000,9.233333,9.940000,14.433333,277.866667,164.500000,3
43,Spencer Rattler,https://247sports.com/player/spencer-rattler-8...,1,73.0,198,99,"Pinnacle (Phoenix, AZ)",Phoenix,AZ,First Round,...,1.366667,7.933333,0.400000,1.633333,8.300000,9.136667,12.133333,155.766667,161.200000,3
44,Ty Simpson,https://247sports.com/player/ty-simpson-46056473/,4,74.0,200,98,"Westview (Martin, TN)",Martin,TN,First Round,...,0.467500,1.475000,0.082500,0.275000,7.550000,7.720000,12.175000,76.050000,131.575000,4
45,Ty Thompson,https://247sports.com/player/ty-thompson-46081...,9,76.0,215,95,"Mesquite (Gilbert, AZ)",Gilbert,AZ,4-7 Round - Day 3,...,0.413333,8.733333,0.253333,6.633333,6.333333,5.093333,10.433333,27.233333,128.433333,3
46,Tyler Buchner,https://247sports.com/player/tyler-buchner-460...,10,74.0,205,95,"Helix (La Jolla, CA)",La Jolla,CA,Second Round,...,0.433333,4.066667,0.656667,4.866667,13.100000,11.743333,17.133333,86.100000,185.700000,3
47,Zach Pyron,https://247sports.com/player/zach-pyron-46059368/,18,75.0,215,90,"Pinson Valley (Pinson, AL)",Pinson,AL,NaN,...,0.400000,2.266667,0.490000,6.933333,5.266667,2.603333,9.500000,77.566667,92.366667,3

Note: Seems like half of the guys in the recruit data are missing in the merged_df (player stats). This may indicate one of the following:

- Did not play multiple years at committed school 
- Data on the school in which they played was not in the college football reference data (lower level schools like d2 most likely)
- Player was not a top 300 recruit.

All of these come as limitations from their respective datasets: 
The recruit data was hevaily filtered to only include players with no missingness and with scouting reports from 247 sports. In the first place, 247 sports is limited in that it only has the top 300 recruits (although I am not worried about this aspect as this list encapsulates most players in the class). 

College Football reference data only contains the top 500 qbs from a given year.


Despite the lack of data that is generated (48 rows); I believe that the data within these rows are quality datapoints and should be examined.

Despite the note above, let's go ahead and merge the team stats to this data.

Note: The way this will work in our model is we train on the teams stats the year before the qb got there. 

This will be done by obtaining the qbs recruiting class year, creating a new column that decrements that number by 1, and then merge then team stats and standings data to the players data via inner merge on the decremented year and team name columns.

In [305]:
print(players['player'].tolist())

['Arch Manning', 'Athan Kaliakmanis', 'Austin Novosad', 'Avery Johnson', 'Beau Allen', 'Behren Morton', 'Brian Maurer', 'Brock Glenn', 'Brock Vandagriff', 'Bryce Young', 'C.J. Stroud', 'Cade Klubnik', 'Cade McNamara', 'Cameron Edge', 'Carson Beck', 'Christopher Vizzina', 'Devin Brown', 'Drew Allar', 'Dylan Lonergan', 'Garrett Nussmeier', 'Gavin Wimsatt', 'Graham Mertz', 'Gunner Stockton', 'Harrison Bailey', 'Haynes King', 'Heinrich Haarberg', 'Hudson Card', 'J.J. McCarthy', 'Jackson Arnold', 'Jalen Milroe', 'Jayden Daniels', 'Kedon Slovis', 'Kenny Minchey', 'Kyle McCord', 'Luke Altmyer', 'Marcel Reed', 'Nico Iamaleava', 'Noah Fifita', 'Preston Stone', 'Rickie Collins', 'Riley Leonard', 'Ryan Hilinski', 'Sam Howell', 'Spencer Rattler', 'Ty Simpson', 'Ty Thompson', 'Tyler Buchner', 'Zach Pyron']

In [306]:
# Scrapper did not obtain player class so manually entered class for each player
# Create a mapping of players to their classes
qb_recruiting_classes = [
    ("Arch Manning", 2023),
    ("Athan Kaliakmanis", 2021),
    ("Austin Novosad", 2023),
    ("Avery Johnson", 2023),
    ("Beau Allen", 2020),
    ("Behren Morton", 2021),
    ("Brian Maurer", 2019),
    ("Brock Glenn", 2023),
    ("Brock Vandagriff", 2021),
    ("Bryce Young", 2020),
    ("C.J. Stroud", 2020),
    ("Cade Klubnik", 2022),
    ("Cade McNamara", 2019),
    ("Cameron Edge", 2022),
    ("Carson Beck", 2020),
    ("Christopher Vizzina", 2023),
    ("Devin Brown", 2022),
    ("Drew Allar", 2022),
    ("Dylan Lonergan", 2023),
    ("Garrett Nussmeier", 2021),
    ("Gavin Wimsatt", 2021),
    ("Graham Mertz", 2019),
    ("Gunner Stockton", 2022),
    ("Harrison Bailey", 2020),
    ("Haynes King", 2020),
    ("Heinrich Haarberg", 2021),
    ("Hudson Card", 2020),
    ("J.J. McCarthy", 2021),
    ("Jackson Arnold", 2023),
    ("Jalen Milroe", 2021),
    ("Jayden Daniels", 2019),
    ("Kedon Slovis", 2019),
    ("Kenny Minchey", 2023),
    ("Kyle McCord", 2021),
    ("Luke Altmyer", 2021),
    ("Marcel Reed", 2023),
    ("Nico Iamaleava", 2023),
    ("Noah Fifita", 2022),
    ("Preston Stone", 2021),
    ("Rickie Collins", 2023),
    ("Riley Leonard", 2021),
    ("Ryan Hilinski", 2019),
    ("Sam Howell", 2019),
    ("Spencer Rattler", 2019),
    ("Ty Simpson", 2022),
    ("Ty Thompson", 2021),
    ("Tyler Buchner", 2021),
    ("Zach Pyron", 2022)
]

# Convert the list into a dataframe
qb_recruiting_classes_df = pd.DataFrame(qb_recruiting_classes, columns=['player', 'recruiting_class'])

In [307]:
# Merge the dataset with the recruiting class information
players = players.merge(qb_recruiting_classes_df, on='player', how='inner')

In [308]:
# Check the results
players

,player,url,rank,height,weight,composite_rating,school_info,city,state,draft_projection,...,TD%,Int,Int%,Y/A,AY/A,Y/C,Y/G,Rate,Counts,recruiting_class
0,Arch Manning,https://247sports.com/player/arch-manning-4608...,1,76.0,215,100,"Isidore Newman (New Orleans, LA)",New Orleans,LA,Round 1 - Top 10,...,5.466667,0.246667,1.300000,8.066667,8.590000,14.400000,117.400000,139.766667,3,2023
1,Athan Kaliakmanis,https://247sports.com/player/athan-kaliakmanis...,26,76.0,205,90,"Antioch (Antioch, IL)",Antioch,IL,4-7 Round - Day 3,...,3.750000,0.555000,3.350000,7.400000,6.635000,13.800000,119.600000,121.300000,2,2021
2,Austin Novosad,https://247sports.com/player/austin-novosad-46...,13,75.0,185,94,"Dripping Springs (Dripping Springs, TX)",Dripping Springs,TX,2-3 Round - Day 2,...,0.000000,0.000000,0.000000,9.400000,9.410000,16.433333,19.866667,156.300000,3,2023
3,Avery Johnson,https://247sports.com/player/avery-johnson-461...,9,74.0,175,95,"Maize (Maize, KS)",Maize,KS,4-7 Round - Day 3,...,6.533333,0.423333,1.500000,7.200000,7.816667,12.366667,155.766667,136.966667,3,2023
4,Beau Allen,https://247sports.com/player/beau-allen-46039461/,64,74.0,203,85,"Lexington Catholic (Lexington, KY)",Lexington,KY,Power 4 Starter,...,0.000000,0.000000,0.000000,6.700000,6.690000,12.400000,25.350000,111.000000,2,2020
5,Behren Morton,https://247sports.com/player/behren-morton-460...,11,74.0,185,94,"Eastland (Eastland, TX)",Eastland,TX,4-7 Round - Day 3,...,4.320000,0.528000,1.960000,5.640000,5.612000,9.060000,161.880000,113.960000,5,2021
6,Brian Maurer,https://247sports.com/player/brian-maurer-4603...,24,75.0,199,88,"West Port (Ocala, FL)",Ocala,FL,Power 4 Starter,...,1.350000,0.315000,3.350000,4.350000,3.125000,10.000000,34.950000,74.300000,2,2019
7,Brock Glenn,https://247sports.com/player/brock-glenn-46114...,21,74.0,195,90,"Lausanne Collegiate School (Covington, TN)",Covington,TN,4-7 Round - Day 3,...,7.833333,0.370000,2.766667,5.533333,5.863333,11.766667,49.466667,114.200000,3,2023
8,Brock Vandagriff,https://247sports.com/player/brock-vandagriff-...,5,75.0,205,97,"Prince Avenue Christian School (Bogart, GA)",Bogart,GA,Second Round,...,3.700000,0.000000,0.000000,3.066667,3.796667,13.800000,6.866667,60.100000,3,2021
9,Bryce Young,https://247sports.com/player/bryce-young-93127/,1,71.0,183,101,"Mater Dei (Santa Ana, CA)",Santa Ana,CA,Round 1 - Top 10,...,7.166667,0.296667,0.866667,8.266667,9.300000,12.966667,207.200000,154.800000,3,2020
10,C.J. Stroud,https://247sports.com/player/cj-stroud-46038118/,3,74.5,194,98,"Rancho Cucamonga (Rancho Cucamonga, CA)",Rancho Cucamonga,CA,First Round,...,10.250000,0.480000,1.450000,9.800000,11.165000,14.150000,326.650000,182.150000,2,2020
11,Cade Klubnik,https://247sports.com/player/cade-klubnik-4605...,2,74.5,186,98,"Austin Westlake (Austin, TX)",Austin,TX,First Round,...,4.425000,0.480000,1.925000,7.075000,7.070000,11.125000,198.425000,133.400000,4,2022
12,Cade McNamara,https://247sports.com/player/cade-mcnamara-93369/,15,73.0,206,90,"Damonte Ranch (Reno, NV)",Reno,NV,4-7 Round - Day 3,...,5.200000,0.253333,1.933333,7.033333,7.186667,11.700000,116.766667,132.566667,3,2019
13,Cameron Edge,https://247sports.com/player/cameron-edge-4609...,60,73.0,190,86,"Smyrna (Smyrna, DE)",Smyrna,DE,Power 4 Starter,...,11.800000,0.250000,5.550000,9.750000,9.605000,15.050000,41.750000,174.250000,2,2022
14,Carson Beck,https://247sports.com/player/carson-beck-46053...,13,76.5,226,92,"Mandarin (Jacksonville, FL)",Jacksonville,FL,4-7 Round - Day 3,...,8.050000,0.462500,3.200000,8.475000,8.597500,13.625000,159.475000,154.675000,4,2020
15,Christopher Vizzina,https://247sports.com/player/christopher-vizzi...,10,75.0,211,95,"Briarwood Christian (Birmingham, AL)",Birmingham,AL,2-3 Round - Day 2,...,2.800000,0.100000,0.700000,5.650000,5.900000,9.500000,54.150000,115.000000,2,2023
16,Devin Brown,https://247sports.com/player/devin-brown-46084...,5,74.5,196,97,"Corner Canyon (Draper, UT)",Draper,UT,2-3 Round - Day 2,...,6.050000,0.085000,1.800000,6.750000,7.135000,12.000000,24.450000,129.050000,2,2022
17,Drew Allar,https://247sports.com/player/drew-allar-46096466/,1,76.5,232,100,"Medina (Medina, OH)",Medina,OH,First Round,...,6.050000,0.287500,1.100000,6.950000,7.680000,11.125000,157.000000,138.650000,4,2022
18,Dylan Lonergan,https://247sports.com/player/dylan-lonergan-46...,16,74.0,215,91,"Brookwood (Snellville, GA)",Snellville,GA,Power 4 Starter,...,0.000000,0.000000,0.000000,4.900000,4.915000,5.300000,11.750000,132.950000,2,2023
19,Garrett Nussmeier,https://247sports.com/player/garrett-nussmeier...,19,73.5,182,94,"Flower Mound Marcus (Flower Mound, TX)",Flower Mound,TX,4-7 Round - Day 3,...,4.860000,0.538000,2.720000,7.460000,7.204000,12.180000,161.360000,134.380000,5,2021
20,Gavin Wimsatt,https://247sports.com/player/gavin-wimsatt-460...,25,75.0,200,91,"Owensboro (Owensboro, KY)",Owensboro,KY,4-7 Round - Day 3,...,2.166667,0.666667,5.700000,4.433333,2.326667,9.733333,79.800000,78.366667,3,2021
21,Graham Mertz,https://247sports.com/player/graham-mertz-4603...,7,75.0,205,93,"Blue Valley North (Mission, KS)",Mission,KS,4-7 Round - Day 3,...,3.700000,0.597500,2.500000,7.025000,6.640000,10.800000,135.500000,133.200000,4,2019
22,Gunner Stockton,https://247sports.com/player/gunner-stockton-4...,7,73.0,220,94,"Rabun County (Tiger, GA)",Tiger,GA,2-3 Round - Day 2,...,6.100000,0.270000,2.733333,7.400000,7.390000,10.966667,110.566667,144.500000,3,2022
23,Harrison Bailey,https://247sports.com/player/harrison-bailey-8...,8,77.0,211,95,"Marietta (Marietta, GA)",Marietta,GA,2-3 Round - Day 2,...,2.950000,0.165000,1.450000,5.400000,5.320000,8.650000,56.150000,108.800000,2,2020
24,Haynes King,https://247sports.com/player/haynes-king-46049...,10,74.5,189,95,"Longview (Longview, TX)",Longview,TX,NaN,...,11.466667,1.000000,12.266667,9.966667,6.730000,18.266667,127.600000,153.133333,3,2020
25,Heinrich Haarberg,https://247sports.com/player/heinrich-haarberg...,40,77.0,185,88,"Kearney Catholic (Kearney, NE)",Kearney,NE,Power 4 Starter,...,2.250000,0.390000,5.050000,5.900000,4.075000,11.350000,52.550000,99.100000,2,2021
26,Hudson Card,https://247sports.com/player/hudson-card-46048...,6,74.5,179,95,"Lake Travis (Austin, TX)",Austin,TX,2-3 Round - Day 2,...,3.866667,0.070000,0.700000,5.800000,6.243333,9.666667,51.200000,114.666667,3,2020
27,J.J. McCarthy,https://247sports.com/player/jj-mccarthy-46042...,6,75.0,190,97,"IMG Academy (La Grange Park, IL)",La Grange Park,IL,Second Round,...,7.300000,0.270000,2.066667,8.700000,9.273333,13.600000,146.833333,158.233333,3,2021
28,Jackson Arnold,https://247sports.com/player/jackson-arnold-46...,4,73.0,205,99,"Denton Guyer (Denton, TX)",Denton,TX,First Round,...,5.350000,0.365000,2.750000,7.000000,6.780000,11.000000,111.250000,133.750000,2,2023
29,Jalen Milroe,https://247sports.com/player/jalen-milroe-4605...,14,75.0,206,94,"Katy Tompkins (Katy, TX)",Katy,TX,4-7 Round - Day 3,...,9.200000,0.422500,2.800000,7.600000,8.167500,13.100000,121.050000,146.400000,4,2021
30,Jayden Daniels,https://247sports.com/player/jayden-daniels-89...,2,75.0,175,97,"Cajon (San Bernardino, CA)",San Bernardino,CA,Second Round,...,4.766667,0.396667,1.700000,8.300000,8.510000,13.600000,201.233333,143.700000,3,2019
31,Kedon Slovis,https://247sports.com/player/kedon-slovis-4604...,75,74.0,186,84,"Desert Mountain (Scottsdale, AZ)",Scottsdale,AZ,4-7 Round - Day 3,...,5.933333,0.936667,2.566667,7.800000,7.860000,11.500000,283.733333,148.133333,3,2019
32,Kenny Minchey,https://247sports.com/player/kenny-minchey-461...,14,73.5,215,93,"Pope John Paul II (Hendersonville, TN)",Hendersonville,TN,4-7 Round - Day 3,...,0.000000,0.000000,0.000000,5.833333,5.846667,6.600000,13.566667,141.400000,3,2023
33,Kyle McCord,https://247sports.com/player/kyle-mccord-46047...,8,75.0,215,97,"St. Joseph's Prep (Philadelphia, PA)",Philadelphia,PA,Second Round,...,5.733333,0.300000,2.333333,9.833333,9.946667,14.100000,124.833333,167.500000,3,2021
34,Luke Altmyer,https://247sports.com/player/luke-altmyer-4605...,30,74.0,190,90,"Starkville (Starkville, MS)",Starkville,MS,NaN,...,7.250000,0.325000,5.650000,6.300000,5.180000,12.600000,34.850000,115.850000,2,2021
35,Marcel Reed,https://247sports.com/player/marcel-reed-46102...,20,73.0,175,90,"Montgomery Bell Academy (Nashville, TN)",Nashville,TN,NaN,...,5.233333,0.600000,2.833333,8.866667,8.626667,14.666667,179.333333,146.500000,3,2023
36,Nico Iamaleava,https://247sports.com/player/nico-iamaleava-46...,2,77.0,195,100,"Warren (Long Beach, CA)",Long Beach,CA,NaN,...,5.050000,0.190000,0.750000,7.400000,8.085000,11.750000,132.000000,140.400000,2,2023
37,Noah Fifita,https://247sports.com/player/noah-fifita-46081...,40,70.0,170,87,"Servite (Anaheim, CA)",Anaheim,CA,Power 4 Starter,...,5.950000,0.490000,1.500000,7.425000,7.957500,12.300000,194.150000,140.225000,4,2022
38,Preston Stone,https://247sports.com/player/preston-stone-460...,18,74.0,205,94,"Parish Episcopal School (Dallas, TX)",Dallas,TX,4-7 Round - Day 3,...,5.525000,0.202500,1.450000,7.275000,7.720000,12.850000,99.800000,131.350000,4,2021
39,Rickie Collins,https://247sports.com/player/rickie-collins-46...,15,74.0,190,92,"Woodlawn (Baton Rouge, LA)",Baton Rouge,LA,4-7 Round - Day 3,...,0.000000,0.000000,0.000000,4.250000,4.250000,4.250000,7.350000,135.700000,2,2023
40,Riley Leonard,https://247sports.com/player/riley-leonard-461...,58,76.0,203,86,"Fairhope (Fairhope, AL)",Fairhope,AL,Power 4 Starter,...,2.833333,0.343333,1.633333,6.800000,6.620000,11.266667,146.666667,123.500000,3,2021
41,Ryan Hilinski,https://247sports.com/player/ryan-hilinski-93478/,6,75.0,230,94,"Orange Lutheran (Orange, CA)",Orange,CA,4-7 Round - Day 3,...,1.350000,0.225000,0.600000,5.750000,5.730000,9.250000,115.650000,113.850000,2,2019
42,Sam Howell,https://247sports.com/player/sam-howell-91707/,4,72.0,225,95,"Sun Valley (Monroe, NC)",Monroe,NC,2-3 Round - Day 2,...,8.166667,0.623333,2.100000,9.233333,9.940000,14.433333,277.866667,164.500000,3,2019
43,Spencer Rattler,https://247sports.com/player/spencer-rattler-8...,1,73.0,198,99,"Pinnacle (Phoenix, AZ)",Phoenix,AZ,First Round,...,7.933333,0.400000,1.633333,8.300000,9.136667,12.133333,155.766667,161.200000,3,2019
44,Ty Simpson,https://247sports.com/player/ty-simpson-46056473/,4,74.0,200,98,"Westview (Martin, TN)",Martin,TN,First Round,...,1.475000,0.082500,0.275000,7.550000,7.720000,12.175000,76.050000,131.575000,4,2022
45,Ty Thompson,https://247sports.com/player/ty-thompson-46081...,9,76.0,215,95,"Mesquite (Gilbert, AZ)",Gilbert,AZ,4-7 Round - Day 3,...,8.733333,0.253333,6.633333,6.333333,5.093333,10.433333,27.233333,128.433333,3,2021
46,Tyler Buchner,https://247sports.com/player/tyler-buchner-460...,10,74.0,205,95,"Helix (La Jolla, CA)",La Jolla,CA,Second Round,...,4.066667,0.656667,4.866667,13.100000,11.743333,17.133333,86.100000,185.700000,3,2021
47,Zach Pyron,https://247sports.com/player/zach-pyron-46059368/,18,75.0,215,90,"Pinson Valley (Pinson, AL)",Pinson,AL,NaN,...,2.266667,0.490000,6.933333,5.266667,2.603333,9.500000,77.566667,92.366667,3,2022

Perect, now let's create a column that decrements it by 1

In [309]:
# Create a new column for the year before enrollment
players['year_before_enrollment'] = players['recruiting_class'] - 1

In [310]:
# Check the results
players

,player,url,rank,height,weight,composite_rating,school_info,city,state,draft_projection,...,Int,Int%,Y/A,AY/A,Y/C,Y/G,Rate,Counts,recruiting_class,year_before_enrollment
0,Arch Manning,https://247sports.com/player/arch-manning-4608...,1,76.0,215,100,"Isidore Newman (New Orleans, LA)",New Orleans,LA,Round 1 - Top 10,...,0.246667,1.300000,8.066667,8.590000,14.400000,117.400000,139.766667,3,2023,2022
1,Athan Kaliakmanis,https://247sports.com/player/athan-kaliakmanis...,26,76.0,205,90,"Antioch (Antioch, IL)",Antioch,IL,4-7 Round - Day 3,...,0.555000,3.350000,7.400000,6.635000,13.800000,119.600000,121.300000,2,2021,2020
2,Austin Novosad,https://247sports.com/player/austin-novosad-46...,13,75.0,185,94,"Dripping Springs (Dripping Springs, TX)",Dripping Springs,TX,2-3 Round - Day 2,...,0.000000,0.000000,9.400000,9.410000,16.433333,19.866667,156.300000,3,2023,2022
3,Avery Johnson,https://247sports.com/player/avery-johnson-461...,9,74.0,175,95,"Maize (Maize, KS)",Maize,KS,4-7 Round - Day 3,...,0.423333,1.500000,7.200000,7.816667,12.366667,155.766667,136.966667,3,2023,2022
4,Beau Allen,https://247sports.com/player/beau-allen-46039461/,64,74.0,203,85,"Lexington Catholic (Lexington, KY)",Lexington,KY,Power 4 Starter,...,0.000000,0.000000,6.700000,6.690000,12.400000,25.350000,111.000000,2,2020,2019
5,Behren Morton,https://247sports.com/player/behren-morton-460...,11,74.0,185,94,"Eastland (Eastland, TX)",Eastland,TX,4-7 Round - Day 3,...,0.528000,1.960000,5.640000,5.612000,9.060000,161.880000,113.960000,5,2021,2020
6,Brian Maurer,https://247sports.com/player/brian-maurer-4603...,24,75.0,199,88,"West Port (Ocala, FL)",Ocala,FL,Power 4 Starter,...,0.315000,3.350000,4.350000,3.125000,10.000000,34.950000,74.300000,2,2019,2018
7,Brock Glenn,https://247sports.com/player/brock-glenn-46114...,21,74.0,195,90,"Lausanne Collegiate School (Covington, TN)",Covington,TN,4-7 Round - Day 3,...,0.370000,2.766667,5.533333,5.863333,11.766667,49.466667,114.200000,3,2023,2022
8,Brock Vandagriff,https://247sports.com/player/brock-vandagriff-...,5,75.0,205,97,"Prince Avenue Christian School (Bogart, GA)",Bogart,GA,Second Round,...,0.000000,0.000000,3.066667,3.796667,13.800000,6.866667,60.100000,3,2021,2020
9,Bryce Young,https://247sports.com/player/bryce-young-93127/,1,71.0,183,101,"Mater Dei (Santa Ana, CA)",Santa Ana,CA,Round 1 - Top 10,...,0.296667,0.866667,8.266667,9.300000,12.966667,207.200000,154.800000,3,2020,2019
10,C.J. Stroud,https://247sports.com/player/cj-stroud-46038118/,3,74.5,194,98,"Rancho Cucamonga (Rancho Cucamonga, CA)",Rancho Cucamonga,CA,First Round,...,0.480000,1.450000,9.800000,11.165000,14.150000,326.650000,182.150000,2,2020,2019
11,Cade Klubnik,https://247sports.com/player/cade-klubnik-4605...,2,74.5,186,98,"Austin Westlake (Austin, TX)",Austin,TX,First Round,...,0.480000,1.925000,7.075000,7.070000,11.125000,198.425000,133.400000,4,2022,2021
12,Cade McNamara,https://247sports.com/player/cade-mcnamara-93369/,15,73.0,206,90,"Damonte Ranch (Reno, NV)",Reno,NV,4-7 Round - Day 3,...,0.253333,1.933333,7.033333,7.186667,11.700000,116.766667,132.566667,3,2019,2018
13,Cameron Edge,https://247sports.com/player/cameron-edge-4609...,60,73.0,190,86,"Smyrna (Smyrna, DE)",Smyrna,DE,Power 4 Starter,...,0.250000,5.550000,9.750000,9.605000,15.050000,41.750000,174.250000,2,2022,2021
14,Carson Beck,https://247sports.com/player/carson-beck-46053...,13,76.5,226,92,"Mandarin (Jacksonville, FL)",Jacksonville,FL,4-7 Round - Day 3,...,0.462500,3.200000,8.475000,8.597500,13.625000,159.475000,154.675000,4,2020,2019
15,Christopher Vizzina,https://247sports.com/player/christopher-vizzi...,10,75.0,211,95,"Briarwood Christian (Birmingham, AL)",Birmingham,AL,2-3 Round - Day 2,...,0.100000,0.700000,5.650000,5.900000,9.500000,54.150000,115.000000,2,2023,2022
16,Devin Brown,https://247sports.com/player/devin-brown-46084...,5,74.5,196,97,"Corner Canyon (Draper, UT)",Draper,UT,2-3 Round - Day 2,...,0.085000,1.800000,6.750000,7.135000,12.000000,24.450000,129.050000,2,2022,2021
17,Drew Allar,https://247sports.com/player/drew-allar-46096466/,1,76.5,232,100,"Medina (Medina, OH)",Medina,OH,First Round,...,0.287500,1.100000,6.950000,7.680000,11.125000,157.000000,138.650000,4,2022,2021
18,Dylan Lonergan,https://247sports.com/player/dylan-lonergan-46...,16,74.0,215,91,"Brookwood (Snellville, GA)",Snellville,GA,Power 4 Starter,...,0.000000,0.000000,4.900000,4.915000,5.300000,11.750000,132.950000,2,2023,2022
19,Garrett Nussmeier,https://247sports.com/player/garrett-nussmeier...,19,73.5,182,94,"Flower Mound Marcus (Flower Mound, TX)",Flower Mound,TX,4-7 Round - Day 3,...,0.538000,2.720000,7.460000,7.204000,12.180000,161.360000,134.380000,5,2021,2020
20,Gavin Wimsatt,https://247sports.com/player/gavin-wimsatt-460...,25,75.0,200,91,"Owensboro (Owensboro, KY)",Owensboro,KY,4-7 Round - Day 3,...,0.666667,5.700000,4.433333,2.326667,9.733333,79.800000,78.366667,3,2021,2020
21,Graham Mertz,https://247sports.com/player/graham-mertz-4603...,7,75.0,205,93,"Blue Valley North (Mission, KS)",Mission,KS,4-7 Round - Day 3,...,0.597500,2.500000,7.025000,6.640000,10.800000,135.500000,133.200000,4,2019,2018
22,Gunner Stockton,https://247sports.com/player/gunner-stockton-4...,7,73.0,220,94,"Rabun County (Tiger, GA)",Tiger,GA,2-3 Round - Day 2,...,0.270000,2.733333,7.400000,7.390000,10.966667,110.566667,144.500000,3,2022,2021
23,Harrison Bailey,https://247sports.com/player/harrison-bailey-8...,8,77.0,211,95,"Marietta (Marietta, GA)",Marietta,GA,2-3 Round - Day 2,...,0.165000,1.450000,5.400000,5.320000,8.650000,56.150000,108.800000,2,2020,2019
24,Haynes King,https://247sports.com/player/haynes-king-46049...,10,74.5,189,95,"Longview (Longview, TX)",Longview,TX,NaN,...,1.000000,12.266667,9.966667,6.730000,18.266667,127.600000,153.133333,3,2020,2019
25,Heinrich Haarberg,https://247sports.com/player/heinrich-haarberg...,40,77.0,185,88,"Kearney Catholic (Kearney, NE)",Kearney,NE,Power 4 Starter,...,0.390000,5.050000,5.900000,4.075000,11.350000,52.550000,99.100000,2,2021,2020
26,Hudson Card,https://247sports.com/player/hudson-card-46048...,6,74.5,179,95,"Lake Travis (Austin, TX)",Austin,TX,2-3 Round - Day 2,...,0.070000,0.700000,5.800000,6.243333,9.666667,51.200000,114.666667,3,2020,2019
27,J.J. McCarthy,https://247sports.com/player/jj-mccarthy-46042...,6,75.0,190,97,"IMG Academy (La Grange Park, IL)",La Grange Park,IL,Second Round,...,0.270000,2.066667,8.700000,9.273333,13.600000,146.833333,158.233333,3,2021,2020
28,Jackson Arnold,https://247sports.com/player/jackson-arnold-46...,4,73.0,205,99,"Denton Guyer (Denton, TX)",Denton,TX,First Round,...,0.365000,2.750000,7.000000,6.780000,11.000000,111.250000,133.750000,2,2023,2022
29,Jalen Milroe,https://247sports.com/player/jalen-milroe-4605...,14,75.0,206,94,"Katy Tompkins (Katy, TX)",Katy,TX,4-7 Round - Day 3,...,0.422500,2.800000,7.600000,8.167500,13.100000,121.050000,146.400000,4,2021,2020
30,Jayden Daniels,https://247sports.com/player/jayden-daniels-89...,2,75.0,175,97,"Cajon (San Bernardino, CA)",San Bernardino,CA,Second Round,...,0.396667,1.700000,8.300000,8.510000,13.600000,201.233333,143.700000,3,2019,2018
31,Kedon Slovis,https://247sports.com/player/kedon-slovis-4604...,75,74.0,186,84,"Desert Mountain (Scottsdale, AZ)",Scottsdale,AZ,4-7 Round - Day 3,...,0.936667,2.566667,7.800000,7.860000,11.500000,283.733333,148.133333,3,2019,2018
32,Kenny Minchey,https://247sports.com/player/kenny-minchey-461...,14,73.5,215,93,"Pope John Paul II (Hendersonville, TN)",Hendersonville,TN,4-7 Round - Day 3,...,0.000000,0.000000,5.833333,5.846667,6.600000,13.566667,141.400000,3,2023,2022
33,Kyle McCord,https://247sports.com/player/kyle-mccord-46047...,8,75.0,215,97,"St. Joseph's Prep (Philadelphia, PA)",Philadelphia,PA,Second Round,...,0.300000,2.333333,9.833333,9.946667,14.100000,124.833333,167.500000,3,2021,2020
34,Luke Altmyer,https://247sports.com/player/luke-altmyer-4605...,30,74.0,190,90,"Starkville (Starkville, MS)",Starkville,MS,NaN,...,0.325000,5.650000,6.300000,5.180000,12.600000,34.850000,115.850000,2,2021,2020
35,Marcel Reed,https://247sports.com/player/marcel-reed-46102...,20,73.0,175,90,"Montgomery Bell Academy (Nashville, TN)",Nashville,TN,NaN,...,0.600000,2.833333,8.866667,8.626667,14.666667,179.333333,146.500000,3,2023,2022
36,Nico Iamaleava,https://247sports.com/player/nico-iamaleava-46...,2,77.0,195,100,"Warren (Long Beach, CA)",Long Beach,CA,NaN,...,0.190000,0.750000,7.400000,8.085000,11.750000,132.000000,140.400000,2,2023,2022
37,Noah Fifita,https://247sports.com/player/noah-fifita-46081...,40,70.0,170,87,"Servite (Anaheim, CA)",Anaheim,CA,Power 4 Starter,...,0.490000,1.500000,7.425000,7.957500,12.300000,194.150000,140.225000,4,2022,2021
38,Preston Stone,https://247sports.com/player/preston-stone-460...,18,74.0,205,94,"Parish Episcopal School (Dallas, TX)",Dallas,TX,4-7 Round - Day 3,...,0.202500,1.450000,7.275000,7.720000,12.850000,99.800000,131.350000,4,2021,2020
39,Rickie Collins,https://247sports.com/player/rickie-collins-46...,15,74.0,190,92,"Woodlawn (Baton Rouge, LA)",Baton Rouge,LA,4-7 Round - Day 3,...,0.000000,0.000000,4.250000,4.250000,4.250000,7.350000,135.700000,2,2023,2022
40,Riley Leonard,https://247sports.com/player/riley-leonard-461...,58,76.0,203,86,"Fairhope (Fairhope, AL)",Fairhope,AL,Power 4 Starter,...,0.343333,1.633333,6.800000,6.620000,11.266667,146.666667,123.500000,3,2021,2020
41,Ryan Hilinski,https://247sports.com/player/ryan-hilinski-93478/,6,75.0,230,94,"Orange Lutheran (Orange, CA)",Orange,CA,4-7 Round - Day 3,...,0.225000,0.600000,5.750000,5.730000,9.250000,115.650000,113.850000,2,2019,2018
42,Sam Howell,https://247sports.com/player/sam-howell-91707/,4,72.0,225,95,"Sun Valley (Monroe, NC)",Monroe,NC,2-3 Round - Day 2,...,0.623333,2.100000,9.233333,9.940000,14.433333,277.866667,164.500000,3,2019,2018
43,Spencer Rattler,https://247sports.com/player/spencer-rattler-8...,1,73.0,198,99,"Pinnacle (Phoenix, AZ)",Phoenix,AZ,First Round,...,0.400000,1.633333,8.300000,9.136667,12.133333,155.766667,161.200000,3,2019,2018
44,Ty Simpson,https://247sports.com/player/ty-simpson-46056473/,4,74.0,200,98,"Westview (Martin, TN)",Martin,TN,First Round,...,0.082500,0.275000,7.550000,7.720000,12.175000,76.050000,131.575000,4,2022,2021
45,Ty Thompson,https://247sports.com/player/ty-thompson-46081...,9,76.0,215,95,"Mesquite (Gilbert, AZ)",Gilbert,AZ,4-7 Round - Day 3,...,0.253333,6.633333,6.333333,5.093333,10.433333,27.233333,128.433333,3,2021,2020
46,Tyler Buchner,https://247sports.com/player/tyler-buchner-460...,10,74.0,205,95,"Helix (La Jolla, CA)",La Jolla,CA,Second Round,...,0.656667,4.866667,13.100000,11.743333,17.133333,86.100000,185.700000,3,2021,2020
47,Zach Pyron,https://247sports.com/player/zach-pyron-46059368/,18,75.0,215,90,"Pinson Valley (Pinson, AL)",Pinson,AL,NaN,...,0.490000,6.933333,5.266667,2.603333,9.500000,77.566667,92.366667,3,2022,2021

Finally, lets begin merging this with the team stats and standings datasets:

In [311]:
# read in both datasets
team_stats = pd.read_excel(r'../Data/Team_Stats_2018_2025.xlsx')

team_standings = pd.read_excel(r'../Data/Team_Standings_2018_2025.xlsx')

In [312]:
team_stats.columns

Index(['Rk', 'School', 'G', 'Pts', 'Pass_Cmp', 'Pass_Att', 'Pass_Pct',
       'Pass_Yds', 'Pass_TD', 'Rush_Att', 'Rush_Yds', 'Rush_Avg', 'Rush_TD',
       'Off_Plays', 'Off_Yds', 'Off_Avg', 'FD_Pass', 'FD_Rush', 'FD_Pen', 'FD',
       'Pen_No.', 'Pen_Yds', 'Fum', 'Int', 'Tot', 'Season'],
      dtype='str')

In [313]:
# Merge team stats with players
players = players.merge(team_stats, left_on=['committed_school', 'year_before_enrollment'], right_on=['School', 'Season'], how='inner')

In [314]:
# Check that no rows were dropped in the merge
players.shape

(48, 85)

In [315]:
# Merge team standings with players
players = players.merge(team_standings, left_on=['committed_school', 'year_before_enrollment'], right_on=['School', 'Season'], how='inner')

In [316]:
# Check that no rows were dropped in the merge
players.shape

(48, 103)

In [317]:
players

,player,url,rank,height,weight,composite_rating,school_info,city,state,draft_projection,...,Conf_Pct,PPG_Off,PPG_Def,SRS,SOS,AP_Pre,AP_High,AP_Rank,Notes,Season_y
0,Arch Manning,https://247sports.com/player/arch-manning-4608...,1,76.0,215,100,"Isidore Newman (New Orleans, LA)",New Orleans,LA,Round 1 - Top 10,...,0.667,34.5,21.6,15.92,8.16,NaN,18.0,25.0,NaN,2022
1,Athan Kaliakmanis,https://247sports.com/player/athan-kaliakmanis...,26,76.0,205,90,"Antioch (Antioch, IL)",Antioch,IL,4-7 Round - Day 3,...,0.429,27.3,30.1,-1.32,2.10,19.0,19.0,NaN,NaN,2020
2,Austin Novosad,https://247sports.com/player/austin-novosad-46...,13,75.0,185,94,"Dripping Springs (Dripping Springs, TX)",Dripping Springs,TX,2-3 Round - Day 2,...,0.778,38.8,27.4,13.44,3.67,11.0,6.0,15.0,NaN,2022
3,Avery Johnson,https://247sports.com/player/avery-johnson-461...,9,74.0,175,95,"Maize (Maize, KS)",Maize,KS,4-7 Round - Day 3,...,0.778,32.3,21.9,16.16,7.95,NaN,11.0,14.0,NaN,2022
4,Beau Allen,https://247sports.com/player/beau-allen-46039461/,64,74.0,203,85,"Lexington Catholic (Lexington, KY)",Lexington,KY,Power 4 Starter,...,0.375,27.2,19.3,5.92,0.15,NaN,NaN,NaN,NaN,2019
5,Behren Morton,https://247sports.com/player/behren-morton-460...,11,74.0,185,94,"Eastland (Eastland, TX)",Eastland,TX,4-7 Round - Day 3,...,0.333,29.1,36.7,-1.67,3.53,NaN,NaN,NaN,NaN,2020
6,Brian Maurer,https://247sports.com/player/brian-maurer-4603...,24,75.0,199,88,"West Port (Ocala, FL)",Ocala,FL,Power 4 Starter,...,0.250,22.8,27.9,0.39,6.05,NaN,NaN,NaN,NaN,2018
7,Brock Glenn,https://247sports.com/player/brock-glenn-46114...,21,74.0,195,90,"Lausanne Collegiate School (Covington, TN)",Covington,TN,4-7 Round - Day 3,...,0.625,36.1,20.6,14.77,3.38,NaN,11.0,11.0,NaN,2022
8,Brock Vandagriff,https://247sports.com/player/brock-vandagriff-...,5,75.0,205,97,"Prince Avenue Christian School (Bogart, GA)",Bogart,GA,Second Round,...,0.778,32.3,20.0,19.33,8.53,4.0,3.0,7.0,NaN,2020
9,Bryce Young,https://247sports.com/player/bryce-young-93127/,1,71.0,183,101,"Mater Dei (Santa Ana, CA)",Santa Ana,CA,Round 1 - Top 10,...,0.750,47.2,18.6,21.11,2.81,2.0,1.0,8.0,NaN,2019
10,C.J. Stroud,https://247sports.com/player/cj-stroud-46038118/,3,74.5,194,98,"Rancho Cucamonga (Rancho Cucamonga, CA)",Rancho Cucamonga,CA,First Round,...,1.000,46.9,13.7,27.39,7.32,5.0,2.0,3.0,NaN,2019
11,Cade Klubnik,https://247sports.com/player/cade-klubnik-4605...,2,74.5,186,98,"Austin Westlake (Austin, TX)",Austin,TX,First Round,...,0.750,26.3,14.8,11.43,2.66,3.0,3.0,14.0,NaN,2021
12,Cade McNamara,https://247sports.com/player/cade-mcnamara-93369/,15,73.0,206,90,"Damonte Ranch (Reno, NV)",Reno,NV,4-7 Round - Day 3,...,0.889,35.2,19.4,16.47,5.47,14.0,4.0,14.0,NaN,2018
13,Cameron Edge,https://247sports.com/player/cameron-edge-4609...,60,73.0,190,86,"Smyrna (Smyrna, DE)",Smyrna,DE,Power 4 Starter,...,0.333,29.3,30.7,3.44,4.36,NaN,NaN,NaN,NaN,2021
14,Carson Beck,https://247sports.com/player/carson-beck-46053...,13,76.5,226,92,"Mandarin (Jacksonville, FL)",Jacksonville,FL,4-7 Round - Day 3,...,0.875,30.8,12.6,17.64,5.21,3.0,3.0,4.0,NaN,2019
15,Christopher Vizzina,https://247sports.com/player/christopher-vizzi...,10,75.0,211,95,"Briarwood Christian (Birmingham, AL)",Birmingham,AL,2-3 Round - Day 2,...,1.000,33.2,20.9,13.59,3.30,4.0,4.0,13.0,NaN,2022
16,Devin Brown,https://247sports.com/player/devin-brown-46084...,5,74.5,196,97,"Corner Canyon (Draper, UT)",Draper,UT,2-3 Round - Day 2,...,0.889,45.7,22.8,19.53,5.53,4.0,2.0,6.0,NaN,2021
17,Drew Allar,https://247sports.com/player/drew-allar-46096466/,1,76.5,232,100,"Medina (Medina, OH)",Medina,OH,First Round,...,0.444,25.0,17.3,11.22,5.53,19.0,4.0,NaN,NaN,2021
18,Dylan Lonergan,https://247sports.com/player/dylan-lonergan-46...,16,74.0,215,91,"Brookwood (Snellville, GA)",Snellville,GA,Power 4 Starter,...,0.750,41.1,18.2,19.66,4.58,1.0,1.0,5.0,NaN,2022
19,Garrett Nussmeier,https://247sports.com/player/garrett-nussmeier...,19,73.5,182,94,"Flower Mound Marcus (Flower Mound, TX)",Flower Mound,TX,4-7 Round - Day 3,...,0.500,32.0,34.9,6.64,7.54,6.0,6.0,NaN,NaN,2020
20,Gavin Wimsatt,https://247sports.com/player/gavin-wimsatt-460...,25,75.0,200,91,"Owensboro (Owensboro, KY)",Owensboro,KY,4-7 Round - Day 3,...,0.333,26.7,32.1,-2.38,3.18,NaN,NaN,NaN,NaN,2020
21,Graham Mertz,https://247sports.com/player/graham-mertz-4603...,7,75.0,205,93,"Blue Valley North (Mission, KS)",Mission,KS,4-7 Round - Day 3,...,0.556,29.7,22.6,7.68,2.60,4.0,4.0,NaN,NaN,2018
22,Gunner Stockton,https://247sports.com/player/gunner-stockton-4...,7,73.0,220,94,"Rabun County (Tiger, GA)",Tiger,GA,2-3 Round - Day 2,...,1.000,38.6,10.2,24.62,5.62,5.0,1.0,1.0,NaN,2021
23,Harrison Bailey,https://247sports.com/player/harrison-bailey-8...,8,77.0,211,95,"Marietta (Marietta, GA)",Marietta,GA,2-3 Round - Day 2,...,0.625,24.2,21.7,5.13,2.74,NaN,NaN,NaN,record adjusted to 0-5-0 by NCAA,2019
24,Haynes King,https://247sports.com/player/haynes-king-46049...,10,74.5,189,95,"Longview (Longview, TX)",Longview,TX,NaN,...,0.500,29.5,22.5,10.02,5.09,12.0,12.0,NaN,NaN,2019
25,Heinrich Haarberg,https://247sports.com/player/heinrich-haarberg...,40,77.0,185,88,"Kearney Catholic (Kearney, NE)",Kearney,NE,Power 4 Starter,...,0.375,23.1,29.4,0.14,5.14,NaN,NaN,NaN,NaN,2020
26,Hudson Card,https://247sports.com/player/hudson-card-46048...,6,74.5,179,95,"Lake Travis (Austin, TX)",Austin,TX,2-3 Round - Day 2,...,0.556,35.2,27.5,12.18,5.80,10.0,9.0,25.0,NaN,2019
27,J.J. McCarthy,https://247sports.com/player/jj-mccarthy-46042...,6,75.0,190,97,"IMG Academy (La Grange Park, IL)",La Grange Park,IL,Second Round,...,0.333,28.3,34.5,-1.25,3.25,16.0,13.0,NaN,NaN,2020
28,Jackson Arnold,https://247sports.com/player/jackson-arnold-46...,4,73.0,205,99,"Denton Guyer (Denton, TX)",Denton,TX,First Round,...,0.333,32.8,30.0,8.52,6.37,9.0,6.0,NaN,NaN,2022
29,Jalen Milroe,https://247sports.com/player/jalen-milroe-4605...,14,75.0,206,94,"Katy Tompkins (Katy, TX)",Katy,TX,4-7 Round - Day 3,...,1.000,48.5,19.4,30.26,9.72,3.0,1.0,1.0,NaN,2020
30,Jayden Daniels,https://247sports.com/player/jayden-daniels-89...,2,75.0,175,97,"Cajon (San Bernardino, CA)",San Bernardino,CA,Second Round,...,0.556,29.9,25.5,5.37,1.67,NaN,23.0,NaN,NaN,2018
31,Kedon Slovis,https://247sports.com/player/kedon-slovis-4604...,75,74.0,186,84,"Desert Mountain (Scottsdale, AZ)",Scottsdale,AZ,4-7 Round - Day 3,...,0.444,26.1,27.0,2.22,3.39,15.0,15.0,NaN,NaN,2018
32,Kenny Minchey,https://247sports.com/player/kenny-minchey-461...,14,73.5,215,93,"Pope John Paul II (Hendersonville, TN)",Hendersonville,TN,4-7 Round - Day 3,...,NaN,31.8,23.0,10.80,3.80,5.0,5.0,18.0,NaN,2022
33,Kyle McCord,https://247sports.com/player/kyle-mccord-46047...,8,75.0,215,97,"St. Joseph's Prep (Philadelphia, PA)",Philadelphia,PA,Second Round,...,1.000,41.0,25.8,21.37,8.99,2.0,2.0,2.0,NaN,2020
34,Luke Altmyer,https://247sports.com/player/luke-altmyer-4605...,30,74.0,190,90,"Starkville (Starkville, MS)",Starkville,MS,NaN,...,0.444,39.2,38.3,8.07,7.57,NaN,NaN,NaN,NaN,2020
35,Marcel Reed,https://247sports.com/player/marcel-reed-46102...,20,73.0,175,90,"Montgomery Bell Academy (Nashville, TN)",Nashville,TN,NaN,...,0.250,22.8,21.2,3.21,3.13,6.0,6.0,NaN,NaN,2022
36,Nico Iamaleava,https://247sports.com/player/nico-iamaleava-46...,2,77.0,195,100,"Warren (Long Beach, CA)",Long Beach,CA,NaN,...,0.750,46.1,22.8,17.90,4.98,NaN,2.0,6.0,NaN,2022
37,Noah Fifita,https://247sports.com/player/noah-fifita-46081...,40,70.0,170,87,"Servite (Anaheim, CA)",Anaheim,CA,Power 4 Starter,...,0.111,17.2,31.4,-12.40,1.44,NaN,NaN,NaN,NaN,2021
38,Preston Stone,https://247sports.com/player/preston-stone-460...,18,74.0,205,94,"Parish Episcopal School (Dallas, TX)",Dallas,TX,4-7 Round - Day 3,...,0.571,38.6,30.9,0.06,-6.14,NaN,16.0,NaN,NaN,2020
39,Rickie Collins,https://247sports.com/player/rickie-collins-46...,15,74.0,190,92,"Woodlawn (Baton Rouge, LA)",Baton Rouge,LA,4-7 Round - Day 3,...,0.750,34.5,22.5,13.29,6.14,NaN,6.0,16.0,NaN,2022
40,Riley Leonard,https://247sports.com/player/riley-leonard-461...,58,76.0,203,86,"Fairhope (Fairhope, AL)",Fairhope,AL,Power 4 Starter,...,0.100,24.8,38.1,-12.88,-1.60,NaN,NaN,NaN,NaN,2020
41,Ryan Hilinski,https://247sports.com/player/ryan-hilinski-93478/,6,75.0,230,94,"Orange Lutheran (Orange, CA)",Orange,CA,4-7 Round - Day 3,...,0.500,30.1,27.2,7.34,5.88,NaN,24.0,NaN,NaN,2018
42,Sam Howell,https://247sports.com/player/sam-howell-91707/,4,72.0,225,95,"Sun Valley (Monroe, NC)",Monroe,NC,2-3 Round - Day 2,...,0.125,27.4,34.5,-4.75,1.70,NaN,NaN,NaN,NaN,2018
43,Spencer Rattler,https://247sports.com/player/spencer-rattler-8...,1,73.0,198,99,"Pinnacle (Phoenix, AZ)",Phoenix,AZ,First Round,...,0.889,48.4,33.3,18.06,6.14,7.0,4.0,4.0,NaN,2018
44,Ty Simpson,https://247sports.com/player/ty-simpson-46056473/,4,74.0,200,98,"Westview (Martin, TN)",Martin,TN,First Round,...,0.875,39.9,20.1,19.62,5.69,1.0,1.0,2.0,NaN,2021
45,Ty Thompson,https://247sports.com/player/ty-thompson-46081...,9,76.0,215,95,"Mesquite (Gilbert, AZ)",Gilbert,AZ,4-7 Round - Day 3,...,0.600,31.3,28.3,0.81,-1.77,9.0,9.0,NaN,NaN,2020
46,Tyler Buchner,https://247sports.com/player/tyler-buchner-460...,10,74.0,205,95,"Helix (La Jolla, CA)",La Jolla,CA,Second Round,...,1.000,33.4,19.7,11.32,1.23,10.0,2.0,5.0,NaN,2020
47,Zach Pyron,https://247sports.com/player/zach-pyron-46059368/,18,75.0,215,90,"Pinson Valley (Pinson, AL)",Pinson,AL,NaN,...,0.250,24.0,33.5,-1.91,3.68,NaN,NaN,NaN,NaN,2021

### Now that we have completed this process, let's clean up the data a bit

First let's remove duplicate columns

In [318]:
# Remove duplicate/ redundant/ not useful columns
players = players.drop(columns=['Player', 'Team', 'Conf_x', 'Rk_x', 'School_x', 'Season_x', 'Rk_y', 'School_y', 'Conf_y', 'Notes', 'Season_y'])

In [319]:
players

,player,url,rank,height,weight,composite_rating,school_info,city,state,draft_projection,...,Conf_W,Conf_L,Conf_Pct,PPG_Off,PPG_Def,SRS,SOS,AP_Pre,AP_High,AP_Rank
0,Arch Manning,https://247sports.com/player/arch-manning-4608...,1,76.0,215,100,"Isidore Newman (New Orleans, LA)",New Orleans,LA,Round 1 - Top 10,...,6.0,3.0,0.667,34.5,21.6,15.92,8.16,NaN,18.0,25.0
1,Athan Kaliakmanis,https://247sports.com/player/athan-kaliakmanis...,26,76.0,205,90,"Antioch (Antioch, IL)",Antioch,IL,4-7 Round - Day 3,...,3.0,4.0,0.429,27.3,30.1,-1.32,2.10,19.0,19.0,NaN
2,Austin Novosad,https://247sports.com/player/austin-novosad-46...,13,75.0,185,94,"Dripping Springs (Dripping Springs, TX)",Dripping Springs,TX,2-3 Round - Day 2,...,7.0,2.0,0.778,38.8,27.4,13.44,3.67,11.0,6.0,15.0
3,Avery Johnson,https://247sports.com/player/avery-johnson-461...,9,74.0,175,95,"Maize (Maize, KS)",Maize,KS,4-7 Round - Day 3,...,7.0,2.0,0.778,32.3,21.9,16.16,7.95,NaN,11.0,14.0
4,Beau Allen,https://247sports.com/player/beau-allen-46039461/,64,74.0,203,85,"Lexington Catholic (Lexington, KY)",Lexington,KY,Power 4 Starter,...,3.0,5.0,0.375,27.2,19.3,5.92,0.15,NaN,NaN,NaN
5,Behren Morton,https://247sports.com/player/behren-morton-460...,11,74.0,185,94,"Eastland (Eastland, TX)",Eastland,TX,4-7 Round - Day 3,...,3.0,6.0,0.333,29.1,36.7,-1.67,3.53,NaN,NaN,NaN
6,Brian Maurer,https://247sports.com/player/brian-maurer-4603...,24,75.0,199,88,"West Port (Ocala, FL)",Ocala,FL,Power 4 Starter,...,2.0,6.0,0.250,22.8,27.9,0.39,6.05,NaN,NaN,NaN
7,Brock Glenn,https://247sports.com/player/brock-glenn-46114...,21,74.0,195,90,"Lausanne Collegiate School (Covington, TN)",Covington,TN,4-7 Round - Day 3,...,5.0,3.0,0.625,36.1,20.6,14.77,3.38,NaN,11.0,11.0
8,Brock Vandagriff,https://247sports.com/player/brock-vandagriff-...,5,75.0,205,97,"Prince Avenue Christian School (Bogart, GA)",Bogart,GA,Second Round,...,7.0,2.0,0.778,32.3,20.0,19.33,8.53,4.0,3.0,7.0
9,Bryce Young,https://247sports.com/player/bryce-young-93127/,1,71.0,183,101,"Mater Dei (Santa Ana, CA)",Santa Ana,CA,Round 1 - Top 10,...,6.0,2.0,0.750,47.2,18.6,21.11,2.81,2.0,1.0,8.0
10,C.J. Stroud,https://247sports.com/player/cj-stroud-46038118/,3,74.5,194,98,"Rancho Cucamonga (Rancho Cucamonga, CA)",Rancho Cucamonga,CA,First Round,...,9.0,0.0,1.000,46.9,13.7,27.39,7.32,5.0,2.0,3.0
11,Cade Klubnik,https://247sports.com/player/cade-klubnik-4605...,2,74.5,186,98,"Austin Westlake (Austin, TX)",Austin,TX,First Round,...,6.0,2.0,0.750,26.3,14.8,11.43,2.66,3.0,3.0,14.0
12,Cade McNamara,https://247sports.com/player/cade-mcnamara-93369/,15,73.0,206,90,"Damonte Ranch (Reno, NV)",Reno,NV,4-7 Round - Day 3,...,8.0,1.0,0.889,35.2,19.4,16.47,5.47,14.0,4.0,14.0
13,Cameron Edge,https://247sports.com/player/cameron-edge-4609...,60,73.0,190,86,"Smyrna (Smyrna, DE)",Smyrna,DE,Power 4 Starter,...,3.0,6.0,0.333,29.3,30.7,3.44,4.36,NaN,NaN,NaN
14,Carson Beck,https://247sports.com/player/carson-beck-46053...,13,76.5,226,92,"Mandarin (Jacksonville, FL)",Jacksonville,FL,4-7 Round - Day 3,...,7.0,1.0,0.875,30.8,12.6,17.64,5.21,3.0,3.0,4.0
15,Christopher Vizzina,https://247sports.com/player/christopher-vizzi...,10,75.0,211,95,"Briarwood Christian (Birmingham, AL)",Birmingham,AL,2-3 Round - Day 2,...,8.0,0.0,1.000,33.2,20.9,13.59,3.30,4.0,4.0,13.0
16,Devin Brown,https://247sports.com/player/devin-brown-46084...,5,74.5,196,97,"Corner Canyon (Draper, UT)",Draper,UT,2-3 Round - Day 2,...,8.0,1.0,0.889,45.7,22.8,19.53,5.53,4.0,2.0,6.0
17,Drew Allar,https://247sports.com/player/drew-allar-46096466/,1,76.5,232,100,"Medina (Medina, OH)",Medina,OH,First Round,...,4.0,5.0,0.444,25.0,17.3,11.22,5.53,19.0,4.0,NaN
18,Dylan Lonergan,https://247sports.com/player/dylan-lonergan-46...,16,74.0,215,91,"Brookwood (Snellville, GA)",Snellville,GA,Power 4 Starter,...,6.0,2.0,0.750,41.1,18.2,19.66,4.58,1.0,1.0,5.0
19,Garrett Nussmeier,https://247sports.com/player/garrett-nussmeier...,19,73.5,182,94,"Flower Mound Marcus (Flower Mound, TX)",Flower Mound,TX,4-7 Round - Day 3,...,5.0,5.0,0.500,32.0,34.9,6.64,7.54,6.0,6.0,NaN
20,Gavin Wimsatt,https://247sports.com/player/gavin-wimsatt-460...,25,75.0,200,91,"Owensboro (Owensboro, KY)",Owensboro,KY,4-7 Round - Day 3,...,3.0,6.0,0.333,26.7,32.1,-2.38,3.18,NaN,NaN,NaN
21,Graham Mertz,https://247sports.com/player/graham-mertz-4603...,7,75.0,205,93,"Blue Valley North (Mission, KS)",Mission,KS,4-7 Round - Day 3,...,5.0,4.0,0.556,29.7,22.6,7.68,2.60,4.0,4.0,NaN
22,Gunner Stockton,https://247sports.com/player/gunner-stockton-4...,7,73.0,220,94,"Rabun County (Tiger, GA)",Tiger,GA,2-3 Round - Day 2,...,8.0,0.0,1.000,38.6,10.2,24.62,5.62,5.0,1.0,1.0
23,Harrison Bailey,https://247sports.com/player/harrison-bailey-8...,8,77.0,211,95,"Marietta (Marietta, GA)",Marietta,GA,2-3 Round - Day 2,...,5.0,3.0,0.625,24.2,21.7,5.13,2.74,NaN,NaN,NaN
24,Haynes King,https://247sports.com/player/haynes-king-46049...,10,74.5,189,95,"Longview (Longview, TX)",Longview,TX,NaN,...,4.0,4.0,0.500,29.5,22.5,10.02,5.09,12.0,12.0,NaN
25,Heinrich Haarberg,https://247sports.com/player/heinrich-haarberg...,40,77.0,185,88,"Kearney Catholic (Kearney, NE)",Kearney,NE,Power 4 Starter,...,3.0,5.0,0.375,23.1,29.4,0.14,5.14,NaN,NaN,NaN
26,Hudson Card,https://247sports.com/player/hudson-card-46048...,6,74.5,179,95,"Lake Travis (Austin, TX)",Austin,TX,2-3 Round - Day 2,...,5.0,4.0,0.556,35.2,27.5,12.18,5.80,10.0,9.0,25.0
27,J.J. McCarthy,https://247sports.com/player/jj-mccarthy-46042...,6,75.0,190,97,"IMG Academy (La Grange Park, IL)",La Grange Park,IL,Second Round,...,2.0,4.0,0.333,28.3,34.5,-1.25,3.25,16.0,13.0,NaN
28,Jackson Arnold,https://247sports.com/player/jackson-arnold-46...,4,73.0,205,99,"Denton Guyer (Denton, TX)",Denton,TX,First Round,...,3.0,6.0,0.333,32.8,30.0,8.52,6.37,9.0,6.0,NaN
29,Jalen Milroe,https://247sports.com/player/jalen-milroe-4605...,14,75.0,206,94,"Katy Tompkins (Katy, TX)",Katy,TX,4-7 Round - Day 3,...,10.0,0.0,1.000,48.5,19.4,30.26,9.72,3.0,1.0,1.0
30,Jayden Daniels,https://247sports.com/player/jayden-daniels-89...,2,75.0,175,97,"Cajon (San Bernardino, CA)",San Bernardino,CA,Second Round,...,5.0,4.0,0.556,29.9,25.5,5.37,1.67,NaN,23.0,NaN
31,Kedon Slovis,https://247sports.com/player/kedon-slovis-4604...,75,74.0,186,84,"Desert Mountain (Scottsdale, AZ)",Scottsdale,AZ,4-7 Round - Day 3,...,4.0,5.0,0.444,26.1,27.0,2.22,3.39,15.0,15.0,NaN
32,Kenny Minchey,https://247sports.com/player/kenny-minchey-461...,14,73.5,215,93,"Pope John Paul II (Hendersonville, TN)",Hendersonville,TN,4-7 Round - Day 3,...,NaN,NaN,NaN,31.8,23.0,10.80,3.80,5.0,5.0,18.0
33,Kyle McCord,https://247sports.com/player/kyle-mccord-46047...,8,75.0,215,97,"St. Joseph's Prep (Philadelphia, PA)",Philadelphia,PA,Second Round,...,5.0,0.0,1.000,41.0,25.8,21.37,8.99,2.0,2.0,2.0
34,Luke Altmyer,https://247sports.com/player/luke-altmyer-4605...,30,74.0,190,90,"Starkville (Starkville, MS)",Starkville,MS,NaN,...,4.0,5.0,0.444,39.2,38.3,8.07,7.57,NaN,NaN,NaN
35,Marcel Reed,https://247sports.com/player/marcel-reed-46102...,20,73.0,175,90,"Montgomery Bell Academy (Nashville, TN)",Nashville,TN,NaN,...,2.0,6.0,0.250,22.8,21.2,3.21,3.13,6.0,6.0,NaN
36,Nico Iamaleava,https://247sports.com/player/nico-iamaleava-46...,2,77.0,195,100,"Warren (Long Beach, CA)",Long Beach,CA,NaN,...,6.0,2.0,0.750,46.1,22.8,17.90,4.98,NaN,2.0,6.0
37,Noah Fifita,https://247sports.com/player/noah-fifita-46081...,40,70.0,170,87,"Servite (Anaheim, CA)",Anaheim,CA,Power 4 Starter,...,1.0,8.0,0.111,17.2,31.4,-12.40,1.44,NaN,NaN,NaN
38,Preston Stone,https://247sports.com/player/preston-stone-460...,18,74.0,205,94,"Parish Episcopal School (Dallas, TX)",Dallas,TX,4-7 Round - Day 3,...,4.0,3.0,0.571,38.6,30.9,0.06,-6.14,NaN,16.0,NaN
39,Rickie Collins,https://247sports.com/player/rickie-collins-46...,15,74.0,190,92,"Woodlawn (Baton Rouge, LA)",Baton Rouge,LA,4-7 Round - Day 3,...,6.0,2.0,0.750,34.5,22.5,13.29,6.14,NaN,6.0,16.0
40,Riley Leonard,https://247sports.com/player/riley-leonard-461...,58,76.0,203,86,"Fairhope (Fairhope, AL)",Fairhope,AL,Power 4 Starter,...,1.0,9.0,0.100,24.8,38.1,-12.88,-1.60,NaN,NaN,NaN
41,Ryan Hilinski,https://247sports.com/player/ryan-hilinski-93478/,6,75.0,230,94,"Orange Lutheran (Orange, CA)",Orange,CA,4-7 Round - Day 3,...,4.0,4.0,0.500,30.1,27.2,7.34,5.88,NaN,24.0,NaN
42,Sam Howell,https://247sports.com/player/sam-howell-91707/,4,72.0,225,95,"Sun Valley (Monroe, NC)",Monroe,NC,2-3 Round - Day 2,...,1.0,7.0,0.125,27.4,34.5,-4.75,1.70,NaN,NaN,NaN
43,Spencer Rattler,https://247sports.com/player/spencer-rattler-8...,1,73.0,198,99,"Pinnacle (Phoenix, AZ)",Phoenix,AZ,First Round,...,8.0,1.0,0.889,48.4,33.3,18.06,6.14,7.0,4.0,4.0
44,Ty Simpson,https://247sports.com/player/ty-simpson-46056473/,4,74.0,200,98,"Westview (Martin, TN)",Martin,TN,First Round,...,7.0,1.0,0.875,39.9,20.1,19.62,5.69,1.0,1.0,2.0
45,Ty Thompson,https://247sports.com/player/ty-thompson-46081...,9,76.0,215,95,"Mesquite (Gilbert, AZ)",Gilbert,AZ,4-7 Round - Day 3,...,3.0,2.0,0.600,31.3,28.3,0.81,-1.77,9.0,9.0,NaN
46,Tyler Buchner,https://247sports.com/player/tyler-buchner-460...,10,74.0,205,95,"Helix (La Jolla, CA)",La Jolla,CA,Second Round,...,9.0,0.0,1.000,33.4,19.7,11.32,1.23,10.0,2.0,5.0
47,Zach Pyron,https://247sports.com/player/zach-pyron-46059368/,18,75.0,215,90,"Pinson Valley (Pinson, AL)",Pinson,AL,NaN,...,2.0,6.0,0.250,24.0,33.5,-1.91,3.68,NaN,NaN,NaN

Next, let's rename certain columns for better clarity

In [320]:
# rename columns to be more descriptive and consistent
players = players.rename(
    columns={
    'rank': 'recruiting_rank',
    'school_info': 'high_school',
    'Season_x': 'Season',
    'G_x': 'games_played_player_after_enrollment',
    'Cmp': 'completions_player_after_enrollment',
    'Att': 'attempts_player_after_enrollment',
    'Cmp%': 'completion_pct_player_after_enrollment',
    'Yds': 'yards_player_after_enrollment',
    'TD': 'touchdowns_player_after_enrollment',
    'TD%': 'touchdown_pct_player_after_enrollment',
    'Int_x': 'interceptions_player_after_enrollment',
    'Int%': 'interception_pct_player_after_enrollment',
    'Y/A': 'yards_per_attempt_player_after_enrollment',
    'AY/A': 'adjusted_yards_per_attempt_player_after_enrollment',
    'Y/C': 'yards_per_completion_player_after_enrollment',
    'Y/G': 'yards_per_game_player_after_enrollment',
    'Rate': 'passing_rating_player_after_enrollment',
    'Counts': 'seasons_played_player_after_enrollment',
    'G_y': 'games_played_team_before_enrollment',
    'Pts': 'ppg_team_before_enrollment',
    'Pass_Cmp': 'passing_completions_team_before_enrollment',
    'Pass_Att': 'passing_attempts_team_before_enrollment',
    'Pass_Pct': 'passing_pct_team_before_enrollment',
    'Pass_Yds': 'passing_yards_team_before_enrollment',
    'Pass_TD': 'passing_touchdowns_team_before_enrollment',
    'Rush_Att': 'rushing_attempts_team_before_enrollment',
    'Rush_Yds': 'rushing_yards_team_before_enrollment',
    'Rush_Avg': 'rushing_average_team_before_enrollment',
    'Rush_TD': 'rushing_touchdowns_team_before_enrollment',
    'Off_Plays': 'offensive_plays_team_before_enrollment',
    'Off_Yds': 'offensive_yards_team_before_enrollment',
    'Off_Avg': 'offensive_average_team_before_enrollment',
    'FD_Pass': 'first_down_passes_team_before_enrollment',
    'FD_Rush': 'first_down_rushes_team_before_enrollment',
    'FD_Pen': 'first_down_penalties_team_before_enrollment',
    'FD': 'first_downs_team_before_enrollment',
    'Pen_No.': 'penalty_counts_team_before_enrollment',
    'Pen_Yds': 'penalty_yards_team_before_enrollment',
    'Fum': 'fumbles_team_before_enrollment',
    'Int_y': 'interceptions_team_before_enrollment',
    'Tot': 'total_turnovers_team_before_enrollment',
    'Ovr_W': 'overall_wins_team_before_enrollment',
    'Ovr_L': 'overall_losses_team_before_enrollment',
    'Ovr_Pct': 'overall_win_pct_team_before_enrollment',
    'Conf_W': 'conference_wins_team_before_enrollment',
    'Conf_L': 'conference_losses_team_before_enrollment',
    'Conf_Pct': 'conference_win_pct_team_before_enrollment',
    'PPG_Off': 'ppg_offense_team_before_enrollment',
    'PPG_Def': 'ppg_defense_team_before_enrollment',
    'SRS': 'srs_team_before_enrollment',
    'SOS': 'sos_team_before_enrollment',
    'AP_Pre': 'ap_pre_team_before_enrollment',
    'AP_High': 'ap_high_team_before_enrollment',
    'AP_Rank': 'ap_rank_team_before_enrollment',
    'Accuracy': 'Accuracy_sentiment_score',
    'Arm Strength': 'Arm_Strength_sentiment_score',
    'Mobility & Athleticism': 'Mobility_and_Athleticism_sentiment_score',
    'NFL / Draft Projection': 'NFL_Draft_Projection_sentiment_score',
    'Pocket Presence': 'Pocket_Presence_sentiment_score',
    'Size & Physical': 'Size_and_Physical_sentiment_score'
    })

Now lets make do a bit more feature engineering:


- create is top ten ranked dummy columns for the following: 'ap_high_team_before_enrollment', 'ap_rank_team_before_enrollment'

- touchdown to interception ratio for the player (this will be the target variable)

In [321]:
# Create column that accesses if player was on a team that finished in the AP top 10 in the year before their enrollment
players['final_ranking_team_AP_top_10_before_enrollment'] = players['ap_rank_team_before_enrollment'].apply(lambda x: 1 if x <= 10 else 0)

# Create column that accesses if player was on a team that got into the AP top 10 at least once during the year before their enrollment
players['highest_ranking_team_AP_top_10_before_enrollment'] = players['ap_high_team_before_enrollment'].apply(lambda x: 1 if x <= 10 else 0)

In [322]:
players

,player,url,recruiting_rank,height,weight,composite_rating,high_school,city,state,draft_projection,...,conference_win_pct_team_before_enrollment,ppg_offense_team_before_enrollment,ppg_defense_team_before_enrollment,srs_team_before_enrollment,sos_team_before_enrollment,ap_pre_team_before_enrollment,ap_high_team_before_enrollment,ap_rank_team_before_enrollment,final_ranking_team_AP_top_10_before_enrollment,highest_ranking_team_AP_top_10_before_enrollment
0,Arch Manning,https://247sports.com/player/arch-manning-4608...,1,76.0,215,100,"Isidore Newman (New Orleans, LA)",New Orleans,LA,Round 1 - Top 10,...,0.667,34.5,21.6,15.92,8.16,NaN,18.0,25.0,0,0
1,Athan Kaliakmanis,https://247sports.com/player/athan-kaliakmanis...,26,76.0,205,90,"Antioch (Antioch, IL)",Antioch,IL,4-7 Round - Day 3,...,0.429,27.3,30.1,-1.32,2.10,19.0,19.0,NaN,0,0
2,Austin Novosad,https://247sports.com/player/austin-novosad-46...,13,75.0,185,94,"Dripping Springs (Dripping Springs, TX)",Dripping Springs,TX,2-3 Round - Day 2,...,0.778,38.8,27.4,13.44,3.67,11.0,6.0,15.0,0,1
3,Avery Johnson,https://247sports.com/player/avery-johnson-461...,9,74.0,175,95,"Maize (Maize, KS)",Maize,KS,4-7 Round - Day 3,...,0.778,32.3,21.9,16.16,7.95,NaN,11.0,14.0,0,0
4,Beau Allen,https://247sports.com/player/beau-allen-46039461/,64,74.0,203,85,"Lexington Catholic (Lexington, KY)",Lexington,KY,Power 4 Starter,...,0.375,27.2,19.3,5.92,0.15,NaN,NaN,NaN,0,0
5,Behren Morton,https://247sports.com/player/behren-morton-460...,11,74.0,185,94,"Eastland (Eastland, TX)",Eastland,TX,4-7 Round - Day 3,...,0.333,29.1,36.7,-1.67,3.53,NaN,NaN,NaN,0,0
6,Brian Maurer,https://247sports.com/player/brian-maurer-4603...,24,75.0,199,88,"West Port (Ocala, FL)",Ocala,FL,Power 4 Starter,...,0.250,22.8,27.9,0.39,6.05,NaN,NaN,NaN,0,0
7,Brock Glenn,https://247sports.com/player/brock-glenn-46114...,21,74.0,195,90,"Lausanne Collegiate School (Covington, TN)",Covington,TN,4-7 Round - Day 3,...,0.625,36.1,20.6,14.77,3.38,NaN,11.0,11.0,0,0
8,Brock Vandagriff,https://247sports.com/player/brock-vandagriff-...,5,75.0,205,97,"Prince Avenue Christian School (Bogart, GA)",Bogart,GA,Second Round,...,0.778,32.3,20.0,19.33,8.53,4.0,3.0,7.0,1,1
9,Bryce Young,https://247sports.com/player/bryce-young-93127/,1,71.0,183,101,"Mater Dei (Santa Ana, CA)",Santa Ana,CA,Round 1 - Top 10,...,0.750,47.2,18.6,21.11,2.81,2.0,1.0,8.0,1,1
10,C.J. Stroud,https://247sports.com/player/cj-stroud-46038118/,3,74.5,194,98,"Rancho Cucamonga (Rancho Cucamonga, CA)",Rancho Cucamonga,CA,First Round,...,1.000,46.9,13.7,27.39,7.32,5.0,2.0,3.0,1,1
11,Cade Klubnik,https://247sports.com/player/cade-klubnik-4605...,2,74.5,186,98,"Austin Westlake (Austin, TX)",Austin,TX,First Round,...,0.750,26.3,14.8,11.43,2.66,3.0,3.0,14.0,0,1
12,Cade McNamara,https://247sports.com/player/cade-mcnamara-93369/,15,73.0,206,90,"Damonte Ranch (Reno, NV)",Reno,NV,4-7 Round - Day 3,...,0.889,35.2,19.4,16.47,5.47,14.0,4.0,14.0,0,1
13,Cameron Edge,https://247sports.com/player/cameron-edge-4609...,60,73.0,190,86,"Smyrna (Smyrna, DE)",Smyrna,DE,Power 4 Starter,...,0.333,29.3,30.7,3.44,4.36,NaN,NaN,NaN,0,0
14,Carson Beck,https://247sports.com/player/carson-beck-46053...,13,76.5,226,92,"Mandarin (Jacksonville, FL)",Jacksonville,FL,4-7 Round - Day 3,...,0.875,30.8,12.6,17.64,5.21,3.0,3.0,4.0,1,1
15,Christopher Vizzina,https://247sports.com/player/christopher-vizzi...,10,75.0,211,95,"Briarwood Christian (Birmingham, AL)",Birmingham,AL,2-3 Round - Day 2,...,1.000,33.2,20.9,13.59,3.30,4.0,4.0,13.0,0,1
16,Devin Brown,https://247sports.com/player/devin-brown-46084...,5,74.5,196,97,"Corner Canyon (Draper, UT)",Draper,UT,2-3 Round - Day 2,...,0.889,45.7,22.8,19.53,5.53,4.0,2.0,6.0,1,1
17,Drew Allar,https://247sports.com/player/drew-allar-46096466/,1,76.5,232,100,"Medina (Medina, OH)",Medina,OH,First Round,...,0.444,25.0,17.3,11.22,5.53,19.0,4.0,NaN,0,1
18,Dylan Lonergan,https://247sports.com/player/dylan-lonergan-46...,16,74.0,215,91,"Brookwood (Snellville, GA)",Snellville,GA,Power 4 Starter,...,0.750,41.1,18.2,19.66,4.58,1.0,1.0,5.0,1,1
19,Garrett Nussmeier,https://247sports.com/player/garrett-nussmeier...,19,73.5,182,94,"Flower Mound Marcus (Flower Mound, TX)",Flower Mound,TX,4-7 Round - Day 3,...,0.500,32.0,34.9,6.64,7.54,6.0,6.0,NaN,0,1
20,Gavin Wimsatt,https://247sports.com/player/gavin-wimsatt-460...,25,75.0,200,91,"Owensboro (Owensboro, KY)",Owensboro,KY,4-7 Round - Day 3,...,0.333,26.7,32.1,-2.38,3.18,NaN,NaN,NaN,0,0
21,Graham Mertz,https://247sports.com/player/graham-mertz-4603...,7,75.0,205,93,"Blue Valley North (Mission, KS)",Mission,KS,4-7 Round - Day 3,...,0.556,29.7,22.6,7.68,2.60,4.0,4.0,NaN,0,1
22,Gunner Stockton,https://247sports.com/player/gunner-stockton-4...,7,73.0,220,94,"Rabun County (Tiger, GA)",Tiger,GA,2-3 Round - Day 2,...,1.000,38.6,10.2,24.62,5.62,5.0,1.0,1.0,1,1
23,Harrison Bailey,https://247sports.com/player/harrison-bailey-8...,8,77.0,211,95,"Marietta (Marietta, GA)",Marietta,GA,2-3 Round - Day 2,...,0.625,24.2,21.7,5.13,2.74,NaN,NaN,NaN,0,0
24,Haynes King,https://247sports.com/player/haynes-king-46049...,10,74.5,189,95,"Longview (Longview, TX)",Longview,TX,NaN,...,0.500,29.5,22.5,10.02,5.09,12.0,12.0,NaN,0,0
25,Heinrich Haarberg,https://247sports.com/player/heinrich-haarberg...,40,77.0,185,88,"Kearney Catholic (Kearney, NE)",Kearney,NE,Power 4 Starter,...,0.375,23.1,29.4,0.14,5.14,NaN,NaN,NaN,0,0
26,Hudson Card,https://247sports.com/player/hudson-card-46048...,6,74.5,179,95,"Lake Travis (Austin, TX)",Austin,TX,2-3 Round - Day 2,...,0.556,35.2,27.5,12.18,5.80,10.0,9.0,25.0,0,1
27,J.J. McCarthy,https://247sports.com/player/jj-mccarthy-46042...,6,75.0,190,97,"IMG Academy (La Grange Park, IL)",La Grange Park,IL,Second Round,...,0.333,28.3,34.5,-1.25,3.25,16.0,13.0,NaN,0,0
28,Jackson Arnold,https://247sports.com/player/jackson-arnold-46...,4,73.0,205,99,"Denton Guyer (Denton, TX)",Denton,TX,First Round,...,0.333,32.8,30.0,8.52,6.37,9.0,6.0,NaN,0,1
29,Jalen Milroe,https://247sports.com/player/jalen-milroe-4605...,14,75.0,206,94,"Katy Tompkins (Katy, TX)",Katy,TX,4-7 Round - Day 3,...,1.000,48.5,19.4,30.26,9.72,3.0,1.0,1.0,1,1
30,Jayden Daniels,https://247sports.com/player/jayden-daniels-89...,2,75.0,175,97,"Cajon (San Bernardino, CA)",San Bernardino,CA,Second Round,...,0.556,29.9,25.5,5.37,1.67,NaN,23.0,NaN,0,0
31,Kedon Slovis,https://247sports.com/player/kedon-slovis-4604...,75,74.0,186,84,"Desert Mountain (Scottsdale, AZ)",Scottsdale,AZ,4-7 Round - Day 3,...,0.444,26.1,27.0,2.22,3.39,15.0,15.0,NaN,0,0
32,Kenny Minchey,https://247sports.com/player/kenny-minchey-461...,14,73.5,215,93,"Pope John Paul II (Hendersonville, TN)",Hendersonville,TN,4-7 Round - Day 3,...,NaN,31.8,23.0,10.80,3.80,5.0,5.0,18.0,0,1
33,Kyle McCord,https://247sports.com/player/kyle-mccord-46047...,8,75.0,215,97,"St. Joseph's Prep (Philadelphia, PA)",Philadelphia,PA,Second Round,...,1.000,41.0,25.8,21.37,8.99,2.0,2.0,2.0,1,1
34,Luke Altmyer,https://247sports.com/player/luke-altmyer-4605...,30,74.0,190,90,"Starkville (Starkville, MS)",Starkville,MS,NaN,...,0.444,39.2,38.3,8.07,7.57,NaN,NaN,NaN,0,0
35,Marcel Reed,https://247sports.com/player/marcel-reed-46102...,20,73.0,175,90,"Montgomery Bell Academy (Nashville, TN)",Nashville,TN,NaN,...,0.250,22.8,21.2,3.21,3.13,6.0,6.0,NaN,0,1
36,Nico Iamaleava,https://247sports.com/player/nico-iamaleava-46...,2,77.0,195,100,"Warren (Long Beach, CA)",Long Beach,CA,NaN,...,0.750,46.1,22.8,17.90,4.98,NaN,2.0,6.0,1,1
37,Noah Fifita,https://247sports.com/player/noah-fifita-46081...,40,70.0,170,87,"Servite (Anaheim, CA)",Anaheim,CA,Power 4 Starter,...,0.111,17.2,31.4,-12.40,1.44,NaN,NaN,NaN,0,0
38,Preston Stone,https://247sports.com/player/preston-stone-460...,18,74.0,205,94,"Parish Episcopal School (Dallas, TX)",Dallas,TX,4-7 Round - Day 3,...,0.571,38.6,30.9,0.06,-6.14,NaN,16.0,NaN,0,0
39,Rickie Collins,https://247sports.com/player/rickie-collins-46...,15,74.0,190,92,"Woodlawn (Baton Rouge, LA)",Baton Rouge,LA,4-7 Round - Day 3,...,0.750,34.5,22.5,13.29,6.14,NaN,6.0,16.0,0,1
40,Riley Leonard,https://247sports.com/player/riley-leonard-461...,58,76.0,203,86,"Fairhope (Fairhope, AL)",Fairhope,AL,Power 4 Starter,...,0.100,24.8,38.1,-12.88,-1.60,NaN,NaN,NaN,0,0
41,Ryan Hilinski,https://247sports.com/player/ryan-hilinski-93478/,6,75.0,230,94,"Orange Lutheran (Orange, CA)",Orange,CA,4-7 Round - Day 3,...,0.500,30.1,27.2,7.34,5.88,NaN,24.0,NaN,0,0
42,Sam Howell,https://247sports.com/player/sam-howell-91707/,4,72.0,225,95,"Sun Valley (Monroe, NC)",Monroe,NC,2-3 Round - Day 2,...,0.125,27.4,34.5,-4.75,1.70,NaN,NaN,NaN,0,0
43,Spencer Rattler,https://247sports.com/player/spencer-rattler-8...,1,73.0,198,99,"Pinnacle (Phoenix, AZ)",Phoenix,AZ,First Round,...,0.889,48.4,33.3,18.06,6.14,7.0,4.0,4.0,1,1
44,Ty Simpson,https://247sports.com/player/ty-simpson-46056473/,4,74.0,200,98,"Westview (Martin, TN)",Martin,TN,First Round,...,0.875,39.9,20.1,19.62,5.69,1.0,1.0,2.0,1,1
45,Ty Thompson,https://247sports.com/player/ty-thompson-46081...,9,76.0,215,95,"Mesquite (Gilbert, AZ)",Gilbert,AZ,4-7 Round - Day 3,...,0.600,31.3,28.3,0.81,-1.77,9.0,9.0,NaN,0,1
46,Tyler Buchner,https://247sports.com/player/tyler-buchner-460...,10,74.0,205,95,"Helix (La Jolla, CA)",La Jolla,CA,Second Round,...,1.000,33.4,19.7,11.32,1.23,10.0,2.0,5.0,1,1
47,Zach Pyron,https://247sports.com/player/zach-pyron-46059368/,18,75.0,215,90,"Pinson Valley (Pinson, AL)",Pinson,AL,NaN,...,0.250,24.0,33.5,-1.91,3.68,NaN,NaN,NaN,0,0

Now, lets create the touchdown/ interception ratio

In [323]:
# Create touchdowns to interception ratio column for player after enrollment
players['TD/INT_Ratio_player_after_enrollment'] = players['touchdowns_player_after_enrollment'] / players['interceptions_player_after_enrollment']

In [324]:
# look at the results
players[['player', 'committed_school', 'touchdowns_player_after_enrollment','interceptions_player_after_enrollment', 'TD/INT_Ratio_player_after_enrollment']]

,player,committed_school,touchdowns_player_after_enrollment,interceptions_player_after_enrollment,TD/INT_Ratio_player_after_enrollment
0,Arch Manning,Texas,0.966667,0.246667,3.918919
1,Athan Kaliakmanis,Minnesota,0.720000,0.555000,1.297297
2,Austin Novosad,Oregon,0.000000,0.000000,NaN
3,Avery Johnson,Kansas State,1.350000,0.423333,3.188976
4,Beau Allen,Kentucky,0.000000,0.000000,NaN
5,Behren Morton,Texas Tech,1.272000,0.528000,2.409091
6,Brian Maurer,Tennessee,0.125000,0.315000,0.396825
7,Brock Glenn,Florida State,0.356667,0.370000,0.963964
8,Brock Vandagriff,Georgia,0.083333,0.000000,inf
9,Bryce Young,Alabama,1.976667,0.296667,6.662921
10,C.J. Stroud,Ohio State,3.410000,0.480000,7.104167
11,Cade Klubnik,Clemson,1.390000,0.480000,2.895833
12,Cade McNamara,Michigan,0.883333,0.253333,3.486842
13,Cameron Edge,Maryland,0.500000,0.250000,2.000000
14,Carson Beck,Georgia,1.232500,0.462500,2.664865
15,Christopher Vizzina,Clemson,0.400000,0.100000,4.000000
16,Devin Brown,Ohio State,0.220000,0.085000,2.588235
17,Drew Allar,Penn State,1.287500,0.287500,4.478261
18,Dylan Lonergan,Alabama,0.000000,0.000000,NaN
19,Garrett Nussmeier,LSU,1.068000,0.538000,1.985130
20,Gavin Wimsatt,Rutgers,0.440000,0.666667,0.660000
21,Graham Mertz,Wisconsin,0.910000,0.597500,1.523013
22,Gunner Stockton,Georgia,0.803333,0.270000,2.975309
23,Harrison Bailey,Tennessee,0.335000,0.165000,2.030303
24,Haynes King,Texas A&M,0.890000,1.000000,0.890000
25,Heinrich Haarberg,Nebraska,0.350000,0.390000,0.897436
26,Hudson Card,Texas,0.376667,0.070000,5.380952
27,J.J. McCarthy,Michigan,1.163333,0.270000,4.308642
28,Jackson Arnold,Oklahoma,0.885000,0.365000,2.424658
29,Jalen Milroe,Alabama,0.970000,0.422500,2.295858
30,Jayden Daniels,Arizona State,1.146667,0.396667,2.890756
31,Kedon Slovis,USC,2.183333,0.936667,2.330961
32,Kenny Minchey,Notre Dame,0.000000,0.000000,NaN
33,Kyle McCord,Ohio State,0.846667,0.300000,2.822222
34,Luke Altmyer,Ole Miss,0.350000,0.325000,1.076923
35,Marcel Reed,Texas A&M,1.203333,0.600000,2.005556
36,Nico Iamaleava,Tennessee,0.930000,0.190000,4.894737
37,Noah Fifita,Arizona,1.535000,0.490000,3.132653
38,Preston Stone,SMU,0.842500,0.202500,4.160494
39,Rickie Collins,LSU,0.000000,0.000000,NaN
40,Riley Leonard,Duke,0.703333,0.343333,2.048544
41,Ryan Hilinski,South Carolina,0.500000,0.225000,2.222222
42,Sam Howell,North Carolina,2.473333,0.623333,3.967914
43,Spencer Rattler,Oklahoma,1.366667,0.400000,3.416667
44,Ty Simpson,Alabama,0.467500,0.082500,5.666667
45,Ty Thompson,Oregon,0.413333,0.253333,1.631579
46,Tyler Buchner,Notre Dame,0.433333,0.656667,0.659898
47,Zach Pyron,Georgia Tech,0.400000,0.490000,0.816327

Note: few players that do not have recorded interceptions.

After further analysis, these players did not get much playing time at their respective schools and are likely not good data points anyway. Therefore, they will be dropped.

In [325]:
# Drop rows where TD/INT ratio is infinite (indicating 0 interceptions) or null (indicating 0 touchdowns and 0 interceptions)
players = players.replace([np.inf, -np.inf], np.nan).dropna(subset=['TD/INT_Ratio_player_after_enrollment'])

In [326]:
# look at the results
players[['player', 'committed_school', 'touchdowns_player_after_enrollment','interceptions_player_after_enrollment', 'TD/INT_Ratio_player_after_enrollment']]

,player,committed_school,touchdowns_player_after_enrollment,interceptions_player_after_enrollment,TD/INT_Ratio_player_after_enrollment
0,Arch Manning,Texas,0.966667,0.246667,3.918919
1,Athan Kaliakmanis,Minnesota,0.720000,0.555000,1.297297
3,Avery Johnson,Kansas State,1.350000,0.423333,3.188976
5,Behren Morton,Texas Tech,1.272000,0.528000,2.409091
6,Brian Maurer,Tennessee,0.125000,0.315000,0.396825
7,Brock Glenn,Florida State,0.356667,0.370000,0.963964
9,Bryce Young,Alabama,1.976667,0.296667,6.662921
10,C.J. Stroud,Ohio State,3.410000,0.480000,7.104167
11,Cade Klubnik,Clemson,1.390000,0.480000,2.895833
12,Cade McNamara,Michigan,0.883333,0.253333,3.486842
13,Cameron Edge,Maryland,0.500000,0.250000,2.000000
14,Carson Beck,Georgia,1.232500,0.462500,2.664865
15,Christopher Vizzina,Clemson,0.400000,0.100000,4.000000
16,Devin Brown,Ohio State,0.220000,0.085000,2.588235
17,Drew Allar,Penn State,1.287500,0.287500,4.478261
19,Garrett Nussmeier,LSU,1.068000,0.538000,1.985130
20,Gavin Wimsatt,Rutgers,0.440000,0.666667,0.660000
21,Graham Mertz,Wisconsin,0.910000,0.597500,1.523013
22,Gunner Stockton,Georgia,0.803333,0.270000,2.975309
23,Harrison Bailey,Tennessee,0.335000,0.165000,2.030303
24,Haynes King,Texas A&M,0.890000,1.000000,0.890000
25,Heinrich Haarberg,Nebraska,0.350000,0.390000,0.897436
26,Hudson Card,Texas,0.376667,0.070000,5.380952
27,J.J. McCarthy,Michigan,1.163333,0.270000,4.308642
28,Jackson Arnold,Oklahoma,0.885000,0.365000,2.424658
29,Jalen Milroe,Alabama,0.970000,0.422500,2.295858
30,Jayden Daniels,Arizona State,1.146667,0.396667,2.890756
31,Kedon Slovis,USC,2.183333,0.936667,2.330961
33,Kyle McCord,Ohio State,0.846667,0.300000,2.822222
34,Luke Altmyer,Ole Miss,0.350000,0.325000,1.076923
35,Marcel Reed,Texas A&M,1.203333,0.600000,2.005556
36,Nico Iamaleava,Tennessee,0.930000,0.190000,4.894737
37,Noah Fifita,Arizona,1.535000,0.490000,3.132653
38,Preston Stone,SMU,0.842500,0.202500,4.160494
40,Riley Leonard,Duke,0.703333,0.343333,2.048544
41,Ryan Hilinski,South Carolina,0.500000,0.225000,2.222222
42,Sam Howell,North Carolina,2.473333,0.623333,3.967914
43,Spencer Rattler,Oklahoma,1.366667,0.400000,3.416667
44,Ty Simpson,Alabama,0.467500,0.082500,5.666667
45,Ty Thompson,Oregon,0.413333,0.253333,1.631579
46,Tyler Buchner,Notre Dame,0.433333,0.656667,0.659898
47,Zach Pyron,Georgia Tech,0.400000,0.490000,0.816327

### Now that those are finished, let's look at missingness.

In [327]:
# Examine missingness in the data
players.isna().sum()

player                                               0
url                                                  0
recruiting_rank                                      0
height                                               0
weight                                               0
                                                    ..
ap_high_team_before_enrollment                      11
ap_rank_team_before_enrollment                      24
final_ranking_team_AP_top_10_before_enrollment       0
highest_ranking_team_AP_top_10_before_enrollment     0
TD/INT_Ratio_player_after_enrollment                 0
Length: 95, dtype: int64

Any of the missingness that is present are in columns that will not be used during the modeling phase. Therefore, let's export the dataset.

In [328]:
# Export the dataframe to a new CSV file
players.to_csv(r'../Data/final_player_data.csv', index=False)